### ISSUE TITLE
NPE on PutObject with Checksum

### ISSUE THREAD

**Issue by william00179** [aws/aws-sdk-java-v2#4608] opened 2023-10-18 02:22 UTC
### Describe the bug

When uploading an object and requesting checksum generation, the following exception will be thrown

```
java.lang.NullPointerException: Cannot read field "value" because "s1" is null
  at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:2077) ~[na:na]
  at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:2070) ~[na:na]
  at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:409) ~[na:na]
  at java.base/java.util.TreeMap.getEntry(TreeMap.java:379) ~[na:na]
  at java.base/java.util.TreeMap.get(TreeMap.java:290) ~[na:na]
  at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.firstMatchingHeader(DefaultSdkHttpFullRequest.java:130) ~[http-client-spi-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.util.HttpChecksumUtils.isHttpChecksumPresent(HttpChecksumUtils.java:153) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.HttpChecksumStage.flexibleChecksumInHeaderRequired(HttpChecksumStage.java:220) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.HttpChecksumStage.execute(HttpChecksumStage.java:83) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.HttpChecksumStage.execute(HttpChecksumStage.java:54) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:222) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[sdk-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53) ~[aws-core-2.21.0.jar!/:na]
  at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:8975) ~[s3-2.21.0.jar!/:na]
```

from code

```java
s3Client.putObject(PutObjectRequest.builder()
                        .key(key)
                        .bucket(bucket)
                        .storageClass(storageClass)
                        .tagging(getTagging())
                        .contentLength((long) buffer.remaining())
                        .contentEncoding(contentEncoding)
                        .contentMD5(md5Digest(buffer))
                        .checksumAlgorithm(ChecksumAlgorithm.CRC32_C)
                        .build(), RequestBody.fromByteBuffer(buffer));
```

### Expected Behavior

The file should upload without exception and return the CRC32C checksum

### Current Behavior

An exception is thrown and the upload fails

### Reproduction Steps

Attempt a Put Object request with checksum algo CRC32C.

### AWS Java SDK version used

2.21.2

### JDK version used

openjdk 21 2023-09-19 LTS OpenJDK Runtime Environment Temurin-21+35 (build 21+35-LTS) OpenJDK 64-Bit Server VM Temurin-21+35 (build 21+35-LTS, mixed mode, sharing)

### Operating System and version

Windows 11

**Comment by felixb** [comment] 2023-10-19 16:40
I've the same problem. Most requests work fine, but some are broken.

**Comment by bhoradc** [comment] 2023-10-19 16:54
Hello @william00179,

Thanks for reporting the issue. Can you please provide more details on `s1`?
`Cannot read field "value" because "s1" is null`

It will be helpful if you can provide a self-contained code snippet that I can use to reproduce the issue. 

Also, kindly confirm if the Java SDK version you are using is 2.21.0 (per your logs) or 2.21.2 (as mentioned in `AWS Java SDK version used` section).

Regards, 
Chaitanya

**Comment by debora-ito** [comment] 2023-10-20 17:49
@william00179 @felixb we can reproduce the issue, we are actively investigating.

**Comment by sugmanue** [comment] 2023-10-20 19:17
@william00179 @felixb we are actively working on this, while we work on this if you're blocked please revert back to using `2.20.162`. We will update this issue when we root cause and find the correct fix.

**Comment by dagnir** [comment] 2023-10-23 12:47
Hi, we have reverted the changes causing this issue in `2.21.6` (via #4621).

**Comment by debora-ito** [comment] 2023-10-24 23:03
The issue is now fixed, so I'll go ahead and close this. 

If you find an issue after upgrading to SDK version `2.21.5`, please open a new issue.

**Closed by debora-ito** 2023-10-24 23:03 UTC
Labels: bug, p1
