### ISSUE TITLE
Regarding URL length of Presigned URL of S3 object

### ISSUE THREAD

**Issue by vishalghanwat321** [aws/aws-sdk-java-v2#4014] opened 2023-05-16 07:48 UTC
### Describe the bug

Hi Team,

If we generate pre-signed URL using access_key and secret_key then url length is shorten and easy to process.
If we generate pre-signed URL using role based Authentification then url do add "X-Amz-Security-Token" variable in generated URL due to which URL length gets increased.

Do we have any tool provided by AWS to shorten this URL as most of the systems are not able to process this longer length URL.

Kindly suggest an approach how to shorten this length of URL.

### Expected Behavior

Can we shorten the length of URL ? 
Or provide a support to shorten the length of URL

### Current Behavior

URL Length is higher and almost containing more than 1800 characters.

### Reproduction Steps

Trying creating Presigned URL using both the approach - 

1 - Using access_key and secret_key
2 - Using role based authentification

### AWS Java SDK version used

mavenBom 'com.amazonaws:aws-java-sdk-bom:1.12.159'

### JDK version used

11

### Operating System and version

MacOS, Windows, Linux, Unix

**Comment by bhoradc** [comment] 2023-05-16 17:44
Closing this as its a duplicate of https://github.com/aws/aws-sdk-java-v2/discussions/4013

**Closed** 2023-05-16 19:08 UTC
Labels: bug, needs-triage
