### ISSUE TITLE
Dynamodb Local Migrate from javax to jakarta for HttpServletRequest, HttpServletResponse

### ISSUE THREAD

**Issue by github4sanjay** [aws/aws-sdk-java-v2#3788] opened 2023-02-23 02:09 UTC
### Describe the feature

It would be great if migrate from javax to jakarta for HttpServletRequest request, HttpServletResponse response.

### Use Case

After spring boot 3 migrated from javax to jakarta, dynamodb local is no longer working in unit tests because of incompatible javax HttpServletRequest, HttpServletResponse.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

implementation("com.amazonaws:DynamoDBLocal:1.21.0")

### JDK version used

17

### Operating System and version

mac os

**Comment by debora-ito** [comment] 2023-02-23 17:59
Duplicate of https://github.com/aws/aws-sdk-java-v2/issues/3605.

The DynamoDB Local team has no plans to support jakarta namespaces.

**Closed by debora-ito** 2023-02-23 17:59 UTC
Labels: feature-request

**Comment by marcuscraske** [comment] 2023-06-06 23:10
Disappointing.

@debora-ito what's the best way to request this? Or does the team plan to discontinue DynamoDB local? Is the alternative to use a container for local testing?

**Comment by debora-ito** [comment] 2023-06-13 18:56
@marcuscraske check my comment on https://github.com/aws/aws-sdk-java-v2/issues/3605, the DynamoDB Local team is working on the migration.
