### ISSUE TITLE
QuickSightClient throws SdkClientException When Delete is Successful

### ISSUE THREAD

**Issue by tonyerskine** [aws/aws-sdk-java-v2#1570] opened 2020-01-03 15:09 UTC
## Expected Behavior
`QuickSightClient.deleteUser(DeleteUserRequest)` should not throw an exception when the user is successfully deleted.

## Current Behavior
`QuickSightClient.deleteUser(DeleteUserRequest)` encounters a null pointer exception because it fails to marshall the 204 No Content response, which AWS Quicksight returns after successfully deleting a user.  The NPE is wrapped in an SdkClientException an thrown.

```
2020-01-03 09:53:36.168 ERROR --- [nio-8080-exec-2] o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [GET] /
Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (null). Response Code: 204, Response Text: No Content
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleSuccessResponse(HandleResponseStage.java:100)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:70)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.quicksight.DefaultQuickSightClient.deleteUser(DefaultQuickSightClient.java:1341)
	at grails4test.ApplicationController.deleteUser(ApplicationController.groovy:85)
	at grails4test.ApplicationController.doStuff(ApplicationController.groovy:44)
	at grails4test.ApplicationController.index(ApplicationController.groovy:23)
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: null
	at software.amazon.awssdk.core.io.SdkFilterInputStream.read(SdkFilterInputStream.java:66)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:522)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:129)
	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:246)
	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1315)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:820)
	at software.amazon.awssdk.protocols.json.internal.dom.JsonDomParser.parse(JsonDomParser.java:39)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:167)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:88)
	at software.amazon.awssdk.core.client.handler.BaseClientHandler.lambda$interceptorCalling$2(BaseClientHandler.java:151)
	at software.amazon.awssdk.core.client.handler.AttachHttpMetadataResponseHandler.handle(AttachHttpMetadataResponseHandler.java:40)
	at software.amazon.awssdk.core.client.handler.AttachHttpMetadataResponseHandler.handle(AttachHttpMetadataResponseHandler.java:28)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleSuccessResponse(HandleResponseStage.java:89)
	... 45 common frames omitted
```

## Possible Solution
I don't have any suggestions here, but here is my current workaround, which I'm not really fond of.
```
try {
    quickSightClient.deleteUser(deleteUserRequest)
} catch (SdkClientException e) {
    if (e.message =~ "No Content")
        log.debug("Ignored No content exception.")
    else {
        log.error(e.message)
        throw e
    }
}
```

## Steps to Reproduce (for bugs)
```
private void deleteQuickSightUser() {
    String awsAccountId = "..."
    String roleName = "cc-embedding_quicksight_dashboard_role"
    String email = "person@company.com"
    String namespace = "default"
    String roleArn = "arn:aws:iam::$awsAccountId:role/$roleName"

    QuickSightClient quickSightClient = QuickSightClient.create()

    User user = quickSightClient.listUsers(ListUsersRequest.builder()
        .awsAccountId(awsAccountId)
        .namespace(namespace)
        .build()
    ).userList().find { it.email() == email }

    if (user) {
        log.error("found the $email user with username: $user.userName")
        DeleteUserRequest deleteUserRequest = DeleteUserRequest.builder()
            .awsAccountId(awsAccountId)
            .namespace(namespace)
            .userName(user.userName)
            .build()
            quickSightClient.deleteUser(deleteUserRequest)
    }
}
```
## Context
This issues is not critical. It's simply cluttering up my code with unnecessary, non-semantic error handling.

## Your Environment
* AWS Java SDK version used: `2.10.41`
* JDK version used: `OpenJDK Runtime Environment Corretto-8.232.09.2 (build 1.8.0_232-b09)`
* Operating System and version: `macOS Catalina v10.15.2 (19C57)`
* Framework: `Grails 4.0.1`
* Language: `Groovy 2.5.6`

**Comment by dagnir** [comment] 2020-01-03 17:47
Hmm this is interesting, according to their service model, `DeleteUser` is expected to return a body, specifically a JSON object with a `RequestId` property:

https://github.com/aws/aws-sdk-java-v2/blob/aad53edd3f4e218ae551fb24bd4df598e2f0b144/services/quicksight/src/main/resources/codegen-resources/service-2.json#L3362-L3368

**Comment by dagnir** [comment] 2020-01-03 17:47
Is this 100% reproducible? Or does the service return a 204 for just a subset of responses?

**Comment by tonyerskine** [comment] 2020-01-03 19:34
Yes, I believe so.  It's happened every time I've tried it.

**Comment by dagnir** [comment] 2020-01-03 21:10
I've sent a question to the QuickSight team regarding this issue since their API docs also mention a response body: 

https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteUser.html

**Comment by debora-ito** [comment] 2020-03-25 23:08
@tonyerskine the QuickSight team released a fix, the deleteUser operation now returns a 200 OK and a RequestId.

Closing this, feel free to reopen if you are still experiencing the issue.

**Closed by debora-ito** 2020-03-25 23:08 UTC
Labels: service-api
