### ISSUE TITLE
AWS SDK2.16.6 does not recognize r5n.metal instance type in describeInstanceTypes API

### ISSUE THREAD

**Issue by bhupali-tambekar-comprinno** [aws/aws-sdk-java-v2#2506] opened 2021-06-01 08:02 UTC
I am using java SDK version 2.16.6. The API call describeInstances returns different value for instance types. Eg. for t2.micro instances, the response is "T2_MICRO" and for r5n.metal instances, the response is "r5n.metal". Subsequent API call to get instance details (describeInstanceTypes API) fails for value of "r5n.metal". 

## Describe the bug

For r5n.metal instance type, describeInstances API returns response as "r5n.metal". When we call another API describeInstanceTypes to get further details using this instance type, we are getting the error message as:
Exception in thread "main" software.amazon.awssdk.services.ec2.model.Ec2Exception: The following supplied instance types do not exist: [r5n.metal] (Service: Ec2, Status Code: 400, Request ID: 768f0a87-c98a-4e97-8e63-7b25df9a5fe2, Extended Request ID: null)

## Expected Behavior

describeInstanceTypes API must return details about the r5n.metal instance

## Current Behavior

describeInstanceTypes API call returns error for instance type r5n.metal
Exception in thread "main" software.amazon.awssdk.services.ec2.model.Ec2Exception: The following supplied instance types do not exist: [r5n.metal] (Service: Ec2, Status Code: 400, Request ID: 768f0a87-c98a-4e97-8e63-7b25df9a5fe2, Extended Request ID: null) 

## Steps to Reproduce

public static MyInstances getInstanceInformationByType(Credential credential, String regionName,  List<String> instanceIds)
      throws Exception {
    AwsCredentials credentials = AWSCustomCredentialHandler.getCredential(credential);
    Ec2Client ec2Client = Ec2Client.builder().credentialsProvider(new AWSStaticCredentialsProvider(credentials))
        .region(Helper.getRegion(regionName)).build();
    DescribeInstancesRequest request = DescribeInstancesRequest.builder().instanceIds(instanceIds).build();
    DescribeInstancesResponse result = ec2Client.describeInstances(request);
    Instance instances = result.reservations().get(0).instances().get(0);
    MyInstances myInstances = new MyInstances();
    InstanceType instanceType = instances.instanceType();
    LOGGER.info("instanceType" + instances.toString());
    DescribeInstanceTypesRequest describeInstanceTypesRequest = DescribeInstanceTypesRequest.builder()
    .instanceTypes(instanceType).build();
    DescribeInstanceTypesResponse response = ec2Client.describeInstanceTypes(describeInstanceTypesRequest);
    ObjectMapper mapper = new ObjectMapper();
    mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    // mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
    LOGGER.info("res" + response.instanceTypes().get(0).vCpuInfo().defaultVCpus());
    if (response.instanceTypes().size() > 0) {
      myInstances.setInstanceId(instanceIds.get(0));
      myInstances.setInstance_type(response.instanceTypes().get(0).instanceType().name());
      myInstances.setProcessorInfo(response.instanceTypes().get(0).processorInfo().supportedArchitecturesAsStrings().get(0));
      myInstances.setCoreCount(response.instanceTypes().get(0).vCpuInfo().defaultVCpus());
      myInstances.setMemoryInfo(response.instanceTypes().get(0).memoryInfo().sizeInMiB());
      LOGGER.info( " " + response.instanceTypes().get(0).vCpuInfo().defaultCores());
    }
    LOGGER.info(myInstances.toString());
    return myInstances;
  }

  // To execute the code above:
public static void main(String[] args) throws Exception {
    Credential credential = new Credential();
    credential.setIam("");
    credential.setSecret_key("");
    List<String> instanceIds = new ArrayList<>();
    instanceIds.add("");
    getInstanceInformationByType(credential, "ap-south-1", instanceIds);
  }

## Context

The application needs to find instance information for all instance types. For r5n.metal instances, the API fails and hence no information is recovered by our application.

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:
AWS Java SDK version used: 2.16.6
JDK version used: 8

**Comment by joviegas** [comment] 2021-06-02 00:23
HI @bhupali-tambekar-comprinno 
Thanks for reporting this. I am looking into this and need some inputs from another team. Will get back to you once they answer my queries.

**Comment by niraj-ranjan-comprinno** [comment] 2021-06-03 06:40
> HI @bhupali-tambekar-comprinno
> Thanks for reporting this. I am looking into this and need some inputs from another team. Will get back to you once they answer my queries.

Hi, Any update

**Comment by joviegas** [comment] 2021-06-03 06:46
The instanceType is available in us-east-1 using the CLI.




> > HI @bhupali-tambekar-comprinno
> > Thanks for reporting this. I am looking into this and need some inputs from another team. Will get back to you once they answer my queries.
> 
> Hi, Any update
Recieved ve
Which region are you calling?



> > HI @bhupali-tambekar-comprinno
> > Thanks for reporting this. I am looking into this and need some inputs from another team. Will get back to you once they answer my queries.
> 
> Hi, Any update

Which region are you calling?

**Comment by bhupali-tambekar-comprinno** [comment] 2021-06-03 07:18
Yes. It's for ap-south-1 region.

**Comment by joviegas** [comment] 2021-06-03 08:09
The Issue is that that  InstanceType Enum doesnot have entry for r5n.metal.
While I am working with Service team to get it updated and it might take time.

Till then I request you to please use **instanceTypeAsString()**

Something like 
```
        final String instanceTypeAsString = result.reservations().get(0).instances().get(0).instanceTypeAsString();

        DescribeInstanceTypesRequest describeInstanceTypesRequest = DescribeInstanceTypesRequest.builder()
                .instanceTypesWithStrings(instanceTypeAsString).build();

```

This will work fine.
I will followup with service team to get the Enum updated.






result.reservations().get(0).instances().get(0).instanceTypeAsString()

**Comment by bhupali-tambekar-comprinno** [comment] 2021-06-03 10:19
Hi @joviegas,

Thanks for the workaround. I am able to get response with instance type passed as string.

I will await for the SDK to be updated with the fix. Hope that this issue will remain in 'open' state until then.

Regards,
Bhupali

**Comment by debora-ito** [comment] 2021-06-17 17:06
@bhupali-tambekar-comprinno `r5n.metal` and other instance types were added in the SDK version `2.16.85`. 

Thank you for reaching out. Closing this one.

**Closed by debora-ito** 2021-06-17 17:06 UTC
Labels: bug, service-api, service:ec2
