### ISSUE TITLE
Enhanced DDB Client - Optimistic locking : DynamoDbVersionAttribute - Missing version match validation for DeleteItem operation in transactWriteItems API

### ISSUE THREAD

**Issue by saikumarsuvanam** [aws/aws-sdk-java-v2#3612] opened 2022-12-13 15:00 UTC
### Describe the bug

Insert a record in DDB table with putoperation and the record version will be 1. Next update the item in the DDB with transactWriteItem API using TransactWriteItemsEnhancedRequest - UpdateItem and then record version will be 2.
Now use the same transactwriteitems API for delete using TransactWriteItemsEnhancedRequest - DeleteItem with the record version 1 . Enhanced client will not check the version and deletes the record which is not aligned with the documentation for delete item operation. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html 

As workaround, we can verify this with condition expression but thats not expected behavior as per documentation. 

### Expected Behavior

TransactWriteItemsEnhancedRequest - DeleteItem operation with   ransactwriteitems API should check the version before deleting the record.

### Current Behavior

Insert a record in DDB table with putoperation and the record version will be 1. Next update the item in the DDB with transactWriteItem API using TransactWriteItemsEnhancedRequest - UpdateItem and then record version will be 2.
Now use the same transactwriteitems API for delete using TransactWriteItemsEnhancedRequest - DeleteItem with the record version 1 . Enhanced client will not check the version and deletes the record which is not aligned with the documentation for delete item operation. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html 

As workaround, we can verify this with condition expression but thats not expected behavior as per documentation. 

### Reproduction Steps

Insert a record in DDB table with putoperation and the record version will be 1. Next update the item in the DDB with transactWriteItem API using TransactWriteItemsEnhancedRequest - UpdateItem and then record version will be 2.
Now use the same transactwriteitems API for delete using TransactWriteItemsEnhancedRequest - DeleteItem with the record version 1 . Enhanced client will not check the version and deletes the record which is not aligned with the documentation for delete item operation. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html 

As workaround, we can verify this with condition expression but thats not expected behavior as per documentation. 

### Possible Solution

Implement the verification step in DeleteItem similar to UpdateItem operation. 
Relevant files: VersionedRecordExtension.java, DeleteItemOperation.java, UpdateItemOperation.java

### AWS Java SDK version used

Version 2

### JDK version used

11

### Operating System and version

macOS 12.6.1

**Comment by debora-ito** [comment] 2022-12-15 19:55
Duplicate of https://github.com/aws/aws-sdk-java-v2/issues/2358.
Closing this one, please track updates in the other link.

**Closed by debora-ito** 2022-12-15 19:55 UTC
Labels: bug, needs-triage
