### ISSUE TITLE
AmazonChime; Status Code: 400; Error Code: ValidationException 

### ISSUE THREAD

**Issue by Thalita-Martins** [aws/aws-sdk-java-v2#4072] opened 2023-06-07 11:50 UTC
### Describe the bug

We use Amazon Chime to create online rooms, but in some requests the AmazonChime error is being returned; Status Code: 400; Error Code: ValidationException, analyzing the documentation of the CreateAttendee and CreateMeeting endpoints that are called to create a room with a participant I couldn't find any information about what this error could be.

The calls are coming back with error logs:

2023-05-24 16:35:44.705 ERROR 1 --- [nio-8080-exec-9] .f.f.c.CustomDataFetcherExceptionHandler : Exception while fetching data (/createAttendeeBySujeitoAtencao) : Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonChime; Status Code: 400; Error Code: ValidationException; Request ID: a0a8c9f9-54d7-4da1-9520-e4c1bfd80c8f; Proxy: null)
com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonChime; Status Code: 400; Error Code: ValidationException; Request ID: a0a8c9f9-54d7-4da1-9520-e4c1bfd80c8f; Proxy: null)

2023-05-24 16:35:40.669 ERROR 1 --- [nio-8080-exec-3] .f.f.c.CustomDataFetcherExceptionHandler : Exception while fetching data (/createAtendeeBySujeitoAtencao) : Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonChime; Status Code: 400; Error Code: ValidationException; Request ID: 6ddd93751-84a3-45ff-8094-b6c0f86c945e; Proxy: null)
com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonChime; Status Code: 400; Error Code: ValidationException; Request ID: 6ddd93751-84a3-45ff-8094-b6c0f86c945e; Proxy: null)

Could you please forward us the requests and the logs of these Request ID mentioned in the text so we can evaluate and verify what error is being sent.

### Expected Behavior

Create a meeting room using the getMeeting endpoint

List meeting participants via the ListAttendees endpoint

Create a new participant for an active meeting using the CreateAttendee endpoint

### Current Behavior

The call to the service is returning the following error:

2023-05-17 09:17:16.460 ERROR 1 --- [nio-8080-exec-6] .f.f.c.CustomDataFetcherExceptionHandler : Exception while fetching data (/createAtendeeBySujeitoAtencao) : Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonChime; Status Code: 400; Error Code: ValidationException; Request ID: e3cb2e45-2655-4eda-86b9-b6f2d73fb3a6; Proxy: null)

com.amazonaws.: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonChime; Status Code: 400; Error Code: ValidationException; Request ID: e3cb2e45-2655-4eda-86b9-b6f2d73fb3a6; Proxy: null)

### Reproduction Steps

Create a meeting room using the getMeeting endpoint

List meeting participants via the ListAttendees endpoint

Create a new participant for an active meeting using the CreateAttendee endpoint

[exemplo da implementação .txt](https://github.com/aws/aws-sdk-java-v2/files/11676476/exemplo.da.implementacao.txt)

### Possible Solution

Forwarding the log or Request ID: a0a8c9f9-54d7-4da1-9520-e4c1bfd80c8f e Request ID: 6dd93751-84a3-45ff-8094-b6c0f86c945e to analyze what the error is 

### AWS Java SDK version used

2.17.178

### JDK version used

Java 18

### Operating System and version

Docker container with Java 19

**Comment by debora-ito** [comment] 2023-06-12 16:35
Closing this for now, as duplicate of https://github.com/aws/aws-sdk-java-v2/discussions/4044.
Will reopen if needed.

**Closed by debora-ito** 2023-06-12 16:35 UTC
Labels: bug
