### ISSUE TITLE
Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-sdk-java-v2#1270] opened 2019-05-28 13:57 UTC
I tried to install documentation by typing

> mvn javadoc:javadoc -e -X

in the "aws-sdk-java-v2-master" folder.

## Expected Behavior
The documentation should install without errors.

## Current Behavior
I received errors. The most common error which seems to be the most problematic error gives this message:

>Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

## Steps to Reproduce (for bugs)
1. Open terminal in macOS
2. Change directory to the "aws-sdk-java-v2-master" folder
3. type 
>mvn javadoc:javadoc -e -X

## Context
I am trying to install documentation.

## Your Environment
* AWS Java SDK version used: v2
* JDK version used: 12.0.1
* Operating System and version: macOS Mojave Version 10.14.5

**Comment by varunnvs92** [comment] 2019-05-28 17:17
This is a JDK bug and is supposed to be fixed in latest version of 12 and 13. See below links:
https://bugs.openjdk.java.net/browse/JDK-8217177
https://bugs.openjdk.java.net/browse/JDK-8212233

If the issue is not resolved, please file a bug in the JDK forums.

**Closed by varunnvs92** 2019-05-28 17:17 UTC
