### ISSUE TITLE
Transfer Manager

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#37] opened 2017-07-03 17:51 UTC
Review the inherited state of the V1 transfer manager and determine which changes are necessary for V2.

(Feel free to comment on this issue with desired changes).

**Comment by abrooksv** [comment] 2017-07-18 22:39
Upload and download return a Transfer which has getProgress(). This returns a simple way to get a percent complete but requires you to do busy loops to update things like UIs.

On the other hand, ProgressListener only returns the bytes transferred causing you to have to do the percentage manually and not very easy since the total size is not exposed.

Better feature parity on the ProgressListener would be nice since that plays better with async

**Comment by millems** [comment] 2017-07-21 20:02
+1 on parity with progress listener. There should probably just be one system between transfer manager and the rest of the SDK for monitoring progress.

**Comment by millems** [comment] 2017-08-10 23:29
Use DirectoryStream for loading files from a directory to avoid having to load all file names into memory.

**Comment by kiiadi** [comment] 2017-08-16 15:17
Unreasonable to expect the thread-pool will be unbounded in order to avoid deadlocks see : https://github.com/aws/aws-sdk-java/issues/939

**Comment by spfink** [comment] 2017-09-13 22:20
TransferManager features requests from v1:

https://github.com/aws/aws-sdk-java/issues/117
https://github.com/aws/aws-sdk-java/issues/284
https://github.com/aws/aws-sdk-java/issues/474
https://github.com/aws/aws-sdk-java/issues/645
https://github.com/aws/aws-sdk-java/issues/893
https://github.com/aws/aws-sdk-java/issues/964
https://github.com/aws/aws-sdk-java/issues/988
https://github.com/aws/aws-sdk-java/issues/1215
https://github.com/aws/aws-sdk-java/issues/1207
https://github.com/aws/aws-sdk-java/issues/1103

**Comment by millems** [comment] 2017-09-29 18:50
https://github.com/aws/aws-sdk-java/issues/1321

**Comment by millems** [comment] 2018-01-02 21:25
Allow using a finite number of threads for background processing. Currently, 1.11.x's `TransferManager` is reported to require an unbounded thread pool to prevent deadlocks.

**Comment by edlunde-dnastar** [comment] 2018-01-02 21:32
+1 for [aws/aws-sdk-java#1103](https://github.com/aws/aws-sdk-java/issues/1103), a request for the ability to limit bandwidth for S3 uploads/downloads. See also the recently closed issue from the aws-cli repo:
https://github.com/aws/aws-cli/issues/1090

This same feature would be similarly useful in the Java SDK to help avoid fees from ISPs for excessive bandwidth usage, or to prevent a single application from overwhelming a network's capacity.

**Comment by zhiqiangZHAO** [comment] 2018-01-04 01:32
+1 for aws/aws-sdk-java#1103, too fast data downloading will saturate the network usage.

**Comment by sql4bucks** [comment] 2018-09-12 21:52
+1 for aws/aws-sdk-java#474. 

 It is very inefficient to write to the file system then upload from the file when I have an object in memory I can serialize directly to a stream. It seems counterintuitive to provide the total content length up front when providing a stream as input - I have to work around it instead of just use it.

**Comment by josephsmithiv** [comment] 2018-09-18 02:55
+1 for https://github.com/aws/aws-sdk-java/issues/893

The primitive AmazonS3 client is capable of uploading and downloading to and from a stream, as well as from a file. The TransferManager can also upload from either a stream or a file, but can only download to a file - not a stream. Symmetry in the interface would be nice. For large files - the kind for which multi-part uploads are most valuable - I can understand that attempting to buffer contents in memory is unwise. However, for small files, I question the value of having to write and read from disk. The download/upload interface is pleasingly abstract, relative to the interface of the primitive client, and I'd like to favor it no matter the size of my files.

**Comment by TeresaP** [comment] 2018-11-29 17:39
I need a method that will let me upload a list of files in parallel and also let me specify the ACL for the files

**Comment by TeresaP** [comment] 2018-11-29 17:43
+1 for aws/aws-sdk-java#1207. I need to be able to upload a lot of files all at once while specifying the ACL. Our customers will be using the CLI to upload files in parallel and I need to closely match the performance in simulating file uploads. If I don't specify the ACL flag, our service cannot read those files and my tests are useless.

**Comment by bisoldi** [comment] 2018-12-18 19:51
+1 for aws/aws-sdk-java#893

My current use-case for this is that I have 100MB+ compressed (GZIP) files on S3 that I need to download and perform some further conversion on.  

It would be great to take advantage of multi-part download and have that stream through Java's GZIPInputStream so that I don't need to download and then uncompress separately.

**Comment by chrisvire** [comment] 2019-03-14 21:03
Is is possible to support the aws cli style of "sync" where TransferManager decides which files are different and only uploads the different ones?

**Comment by alexmojaki** [comment] 2019-04-19 13:06
Reminder that for https://github.com/aws/aws-sdk-java/issues/474, I have written [a library](https://github.com/alexmojaki/s3-stream-upload) using the SDK v1 which allows streaming data to S3 without knowing the size beforehand and without keeping it all in memory or writing to disk. You may find the source code helpful for implementing the feature in v2. I am not planning on porting the library to use v2. Implementing the feature in v2 may have advantages over my library, e.g. by using asnyc non-blocking I/O instead of many threads.

@sql4bucks see the library if you haven't already, you may find it useful.

**Comment by dagnir** [comment] 2019-04-19 20:44
Thanks @alexmojaki. We will keep this in mind when investigating how to address https://github.com/aws/aws-sdk-java/issues/474.

**Comment by dagnir** [comment] 2019-04-23 20:14
Hi all,

For anyone interested, here is the current design for TransferManager: https://github.com/aws/aws-sdk-java-v2/tree/master/docs/design/services/s3/transfermanager. Feel free to leave feedback and comments!

The README will be updated soon to go into depth on current prototype.

**Comment by abhimanyu4211** [comment] 2019-05-01 18:03
> 
> 
> Hi all,
> 
> For anyone interested, here is the current design for TransferManager: https://github.com/aws/aws-sdk-java-v2/tree/master/docs/design/services/s3/transfermanager. Feel free to leave feedback and comments!
> 
> The README will be updated soon to go into depth on current prototype.

When can this be expected for use? And which version?

**Comment by debora-ito** [comment] 2019-07-18 22:29
Feature request from v1: 

Provide getSubTransfers() method for MultipleFileDownload - https://github.com/aws/aws-sdk-java/issues/785

**Comment by debora-ito** [comment] 2019-10-10 01:09
Feature request from v1: Support for custom collections of transfers in TransferManager - https://github.com/aws/aws-sdk-java/issues/1541

**Comment by dagnir** [comment] 2019-10-22 21:29
From V1: 
 - Support sync: https://github.com/aws/aws-sdk-java-v2/issues/37

**Comment by debora-ito** [comment] 2020-01-03 01:14
Feature request from V1: 
- Replace S3 downloadInParallel by using Content-Range requests instead of undocumented S3 part requests - https://github.com/aws/aws-sdk-java/issues/1303

**Comment by fleiber** [comment] 2020-04-10 11:09
> Hi all,
> 
> For anyone interested, here is the current design for TransferManager: https://github.com/aws/aws-sdk-java-v2/tree/master/docs/design/services/s3/transfermanager. Feel free to leave feedback and comments!
> 
> The README will be updated soon to go into depth on current prototype.

Any update on this? Any idea when it could be ready?

**Comment by agkeahan** [comment] 2020-04-12 23:34
> 
> 
> Hi all,
> 
> For anyone interested, here is the current design for TransferManager: https://github.com/aws/aws-sdk-java-v2/tree/master/docs/design/services/s3/transfermanager. Feel free to leave feedback and comments!
> 
> The README will be updated soon to go into depth on current prototype.

Will there be a separate high-level GlacierTransferManager for Glacier vaults/archives, or will Glacier operations be absorbed into S3?

**Comment by vincent-dm** [comment] 2021-01-28 15:52
Any update on this? Any idea when it could be ready?

**Comment by jereztech** [comment] 2021-05-18 01:04
Rarely does a backend create files on the server, so using a directory as a source for uploads causes unnecessary memory and performance problems. Ideally, the backend sends the MultipartFile received from the frontend without having to save it internally on the server and then upload it, this is frustrating and unnecessary. Cloud computing is expensive, therefore creating unnecessary directories is not reasonably acceptable. 

Proposal:
In TransferManager, create a new method using InputStream instead of File:
MultipleFileUpload uploadFileList(String bucketName, List<InputStream> streams)
Is very important to use InputStream because many times we manipulate the files sent by users, for example reducing images.

[#2572](https://github.com/aws/aws-sdk-java/issues/2572)

**Comment by zoewangg** [comment] 2021-08-10 22:00
Hi all, we have released the Developer Preview of Transfer Manager. Currently it supports single file upload and download, and we are actively working on adding more features.

```xml
<dependency>
  <groupId>software.amazon.awssdk</groupId>
  <artifactId>s3-transfer-manager</artifactId>
  <version>2.17.16-PREVIEW</version>
</dependency>
```

You can find sample code here: https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/s3-transfer-manager

Give it a try and let us know what you think!  🙂

**Comment by pkgonan** [comment] 2021-09-13 06:59
@zoewangg 
Hi. Is there any support plan that reactive input like Flux? Currently, it seems that only file path is supported as input.

**Comment by ashishdhingra** [comment] 2021-09-27 20:15
https://github.com/aws/aws-sdk-java-v2/issues/2731

**Comment by exoego** [comment] 2021-11-07 12:57
[downloadDirectory](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#downloadDirectory-java.lang.String-java.lang.String-java.io.File-) is missing.

**Comment by mjdinsmore** [comment] 2021-11-15 23:58
When using the TransferManager API (see https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html), I'm experiencing an exception like?
`Caused by: java.util.concurrent.CompletionException: software.amazon.awssdk.crt.s3.CrtS3RuntimeException: Retry cannot be attempted because the maximum number of retries has been exceeded. AWS_IO_MAX_RETRIES_EXCEEDED(1069)`

Is there any way to ensure the underlying S3Client is okay when using the TransferManager?  How can you validate that it is properly configured?  Setting it up is straightforward:
`S3TransferManager transferManager = S3TransferManager.builder()
                .s3ClientConfiguration(b ->
                        b.credentialsProvider(AwsUtils.awsCredentialsProvider())
                                .region(Region.US_EAST_1)
                                .targetThroughputInGbps(1.0)
                                .minimumPartSizeInBytes(FileUtils.ONE_MB)
                                .maxConcurrency(4)
                )
                .build();`

but there's no way, that I'm aware of, to see if things are okay.

**Comment by Zhenye-Na** [comment] 2021-12-17 01:56
https://github.com/aws/aws-sdk-java/issues/1572

**Comment by adrian-skybaker** [comment] 2022-04-07 06:32
Do you have a target in mind for moving to a non-preview release?

**Comment by djchapm** [comment] 2022-06-21 15:57
Can you confirm if #474 (highest upvoted above) will get prioritized?

**Comment by zoewangg** [comment] 2022-06-21 17:39
@djchapm as mentioned in https://github.com/aws/aws-sdk-java-v2/issues/2714#issuecomment-1162017331, this feature is in our backlog, and we will track it in https://github.com/aws/aws-sdk-java-v2/issues/139

**Comment by kingan379** [comment] 2022-08-03 12:08
@zoewangg what about aborting the upload? Is there a plan to add a method for that in TransferManager v2 (as it was in v1)?

**Comment by zoewangg** [comment] 2022-08-03 16:20
@kingan379 you can cancel the transfer by cancelling the future in the returned upload, `CompletableFuture#cancel`. Note that the current implementation is to stop scheduling new multipart uploads, wait for all existing uploads to finish and then invoke abortMultipart API, so it may not abort the transfer immediately. See https://github.com/aws/aws-sdk-java-v2/issues/3274#issuecomment-1182442921 for more details.

**Comment by kingan379** [comment] 2022-08-05 16:41
@zoewangg thank you,
Another question, is there any way to get uploadId from S3TransferManager?

**Comment by kingan379** [comment] 2022-08-11 22:18
Is there a plan to support InputStream in S3TransferManager?

**Comment by AlexOkayJ** [comment] 2022-08-23 17:27
Hello!
Is there are any plans to support parallel upload/download with AmazonS3Encryption client?

**Comment by zoewangg** [comment] 2022-12-20 21:05
Hi all, we are pleased to announce the general availability of the S3 Transfer Manager 🎉.  Check out the following links to get started.
[Blog post](https://aws.amazon.com/blogs/developer/introducing-crt-based-s3-client-and-the-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/)
[Dev Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html)
[Javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/transfer/s3/S3TransferManager.html)

As always, we welcome feature requests, bug reports and feedback.🙂 I'm going to close this issue. Feel free to create new GH issues.

**Closed by zoewangg** 2022-12-20 21:05 UTC
Labels: 1.x Parity, feature-request, transfer-manager, p1

**Comment by zoewangg** [comment] 2022-12-20 21:07
> Is there are any plans to support parallel upload/download with AmazonS3Encryption client?

Hi @AlexOkayJ, client encryption support is tracked in https://github.com/aws/aws-sdk-java-v2/issues/34

**Comment by zoewangg** [comment] 2022-12-20 21:26
> Is there a plan to support InputStream in S3TransferManager?

Hi @kingan379, it's supported now. You can use `AsyncRequestBody#fromInputStream` and pass it to `S3TransferManager#upload`. 
```
        S3TransferManager transferManager = S3TransferManager.create();

        UploadRequest uploadRequest = UploadRequest.builder()
                                                   .requestBody(AsyncRequestBody.fromInputStream(inputStream))
                                                   .putObjectRequest(req -> req.bucket("bucket").key("key"))
                                                   .build();

        Upload upload = transferManager.upload(uploadRequest);
```

**Comment by daniel-teodoro** [comment] 2022-12-27 23:00
Hi!

I'm getting this error with sample code on eclipse:

![image](https://user-images.githubusercontent.com/32025525/209734462-741bdd0b-3d12-4627-ab6c-732d45f78548.png)

"The method s3ClientConfiguration((<no type> cfg) -> {}) is undefined for the type S3TransferManager.Builder"

How can I fix it, please ?

Thanks

**Comment by daniel-teodoro** [comment] 2022-12-28 22:06
I commented this s3ClientConfiguration, but now, the join() method is throwing this error:
"Unable to execute HTTP request: SSLEngine closed already".
Would anyone have a clue?
Thanks again!


	     S3TransferManager transferManager = S3TransferManager.create();
	     
	     GetObjectRequest getObjectRequest = GetObjectRequest.builder()
	    		 //.overrideConfiguration(SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES)
	                .bucket(AWS_S3_BUCKET_NAME)
	                .key(dirS3)
	                .build();

	     DownloadFileRequest downloadFileRequest =
	    		 DownloadFileRequest.builder()
	             	.getObjectRequest(getObjectRequest)
	                	.destination(Paths.get(dirLocalArqDownload))
	                    .addTransferListener(LoggingTransferListener.create())
	                    .build();
	     
	     FileDownload download = transferManager.downloadFile(downloadFileRequest);
	     download.completionFuture().join();


---------------------------------------------


Exception in thread "main" java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: SSLEngine closed already
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
