### ISSUE TITLE
DynamoDbEnhancedClient :  java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by laulee5135** [aws/aws-sdk-java-v2#3701] opened 2023-01-18 02:34 UTC
### Describe the bug

Use DynamoDbEnhancedClient to perform query operation, java.lang.OutOfMemoryError: Metaspace occurs, after dump file analysis, LambdaToMethodBridgeBuilder overflows

### Expected Behavior

no OOM

### Current Behavior

java.lang.OutOfMemoryError: Metaspace

### Reproduction Steps

```
public class DynamoDBStoreService{
     
     DynamoDbClient ddb = dynamoDbClientBuilder.build();
     DynamoDbEnhancedClient enhancedClient = DynamoDbEnhancedClient.builder()
                    .dynamoDbClient(ddb)
                    .build();

    public void getKlineHistory(){
      //core code
      String partitionVal = "";
      List<KlineVo> klineVos  = new ArrayList<>();
      DynamoDbTable<KlineVo> mappedTable = enhancedClient.table("kline", TableSchema.fromBean(KlineVo.class));
      QueryConditional queryConditional = QueryConditional.keyEqualTo(Key.builder().partitionValue(partitionVal).build());
      QueryEnhancedRequest queryEnhancedRequest = QueryEnhancedRequest.builder()
                        .queryConditional(queryConditional)
                        .scanIndexForward(false)
                        .limit(100)
                        .build();
      PageIterable<KlineVo> query = mappedTable.query(queryEnhancedRequest);
      Iterator<KlineVo> iterator = query.items().iterator();
      while (iterator.hasNext()) {
                    KlineVo klineVo = iterator.next();
                    klineVos.add(klineVo);
      }
      System.out.println(klineVos);
   }
   
}

```

It can be reproduced by pressure testing,  You will find that the number of classes begins to increase significantly, and the metaspace also begins to increase

### AWS Java SDK version used

2.19.17

### JDK version used

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)

### Operating System and version

Linux

**Comment by debora-ito** [comment] 2023-01-18 20:11
Hi @laulee5135 thank you for reaching out.

We are aware of the issue and investigating what could be the root cause. 

So far we identified that the issue occurs when using Java 17, and it has to do with `TableSchema.fromClass()` or `TableSchema.fromBean()` calls. Reducing the times those calls are made should help.

We'll post any updates we get from the investigation.

**Comment by zoewangg** [comment] 2023-01-19 18:18
To add to what Debora said, it is related to [JEP 371: Hidden Classes](https://openjdk.org/jeps/371) introduced in JDK 15. The generated classes are not able to be unloaded anymore, and that's why it will run out of metaspace if you are invoking it repeatably. We will consider adding a cache in the SDK.  I should note that it's recommended to reuse `TableSchme#fromBean/fromClass` instead of invoking them per request.

**Comment by zoewangg** [comment] 2023-02-03 18:32
We have released the change to cache `BeanTableSchema` and `ImmutableTableSchme` via #3710. Closing the issue.

**Closed by zoewangg** 2023-02-03 18:32 UTC
Labels: bug, dynamodb-enhanced
