### ISSUE TITLE
finalizeMultipartUpload is throwing 404 error

### ISSUE THREAD

**Issue by savan143** [aws/aws-sdk-java-v2#5226] opened 2024-05-16 13:43 UTC
### Describe the bug

We are utilizing multipart upload feature in our application. It has 4 steps.

InitializeMultipartUpload
GenerateS3SignedUrl
Upload Parts
FinalizeMultipartUpload
Here whole flow was working fine before we enabled public access block on our S3s.
After enabling this public access block we are doing all transaction using CF url instead of direct s3 url. Here First 3 steps are working fine where 4th step(FinalizeMultipartUpload) is throwing below error.

The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: DF9DESQHKG183Q2D; S3 Extended Request ID: GAVKk1LSbjHWN6pMDw3lA3b8YjF8crE+xg8YyVjPiVxnv5wSrx1PqBcnpk3ry90r5HGOof11GaYxyz=; Proxy: null)

Can someone please help us finding the missing logic here if we are missing anything?

Current SDK version we are using is 1.12.410.

### Expected Behavior

It was working fine before public access block and that's what we are expecting.

### Current Behavior

FinalizeMultipartUpload method is throwing below error.

The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: DF9DESQHKG183Q2D; S3 Extended Request ID: GAVKk1LSbjHWN6pMDw3lA3b8YjF8crE+xg8YyVjPiVxnv5wSrx1PqBcnpk3ry90r5HGOof11GaYxyz=; Proxy: null)

### Reproduction Steps

Mentioned steps in description which we are following currently in our application.

### AWS Java SDK version used

1.12.410

### JDK version used

java-base:17-temurin

### Operating System and version

Java

**Comment by savan143** [comment] 2024-05-16 14:05
@zoewangg @dagnir @cenedhryn @varunnvs92 @shorea @kiiadi @joviegas @spfink @gosar @davidh44 @sugmanue @Bennett-Lynch any input would be appreciated.

**Comment by debora-ito** [comment] 2024-05-17 23:52
Duplicate of https://github.com/aws/aws-sdk-java/issues/3111. Please track this in the v1 repo.

**Closed by debora-ito** 2024-05-17 23:52 UTC
Labels: duplicate
