### ISSUE TITLE
DynamoDb Enhanced - VersionedRecordExtension doesn't properly handle attribute names with special characters.

### ISSUE THREAD

**Issue by The-Zona-Zoo** [aws/aws-sdk-java-v2#3279] opened 2022-07-01 22:50 UTC
### Describe the bug

Using the DynamoDb Enhanced API with the `@DynamoDbVersionAttribute` extension with an attribute name that contains a special character (with respect to the parsing rules), in this case`_`, causes an exception during `DynamoDbEnhancedClient#putItem(PutItemEnhancedRequest)` calls.

This is almost certainly due to [`VersionedRecordExtension`](https://github.com/aws/aws-sdk-java-v2/blob/c976d74f018081858118d26e580a6032d34d69b8/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtension.java#L126) not making proper use of the `Expression.expressionNames()` option, as pointed out by this [slightly-related satck overflow post](https://stackoverflow.com/questions/42198091/dynamodb-why-cant-i-use-an-as-a-prefix-in-my-key-condition-expression). Using `expresionNames` should resolve this problem.

### Expected Behavior

The version condition check should succeed regardless of the naming scheme used for the `@DynamoDbVersionAttribute`.

### Current Behavior

Currently, using an attribute name that contains (maybe just begins with I'm not sure what the parsing rules are) `_` will cause the following error:
```
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid ConditionExpression: Syntax error; token: "_", near: "_version" (Service: DynamoDb, Status Code: 400, Request ID: QRI2BVSTOEDPTJKVAP8VLNV8R7VV4KQNSO5AEMVJF66Q9ASUAAJG)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[AwsJavaSdk-Core-2.0.jar:?]
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[AwsJavaSdk-Core-AwsCore-2.0.jar:?]
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.putItem(DefaultDynamoDbClient.java:3970) ~[AwsJavaSdk-DynamoDb-2.0.jar:?]
	at software.amazon.awssdk.enhanced.dynamodb.internal.operations.CommonOperation.execute(CommonOperation.java:114) ~[AwsJavaSdk-DynamoDb-Enhanced-2.0.jar:?]
	at software.amazon.awssdk.enhanced.dynamodb.internal.operations.TableOperation.executeOnPrimaryIndex(TableOperation.java:59) ~[AwsJavaSdk-DynamoDb-Enhanced-2.0.jar:?]
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.putItem(DefaultDynamoDbTable.java:201) ~[AwsJavaSdk-DynamoDb-Enhanced-2.0.jar:?]
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.putItem(DefaultDynamoDbTable.java:209) ~[AwsJavaSdk-DynamoDb-Enhanced-2.0.jar:?]
	at software.amazon.awssdk.enhanced.dynamodb.internal.client.DefaultDynamoDbTable.putItem(DefaultDynamoDbTable.java:214) ~[AwsJavaSdk-DynamoDb-Enhanced-2.0.jar:?]
```

### Reproduction Steps

Using the DynamoDb enhanced API, attempt to save (`putItem`) with the `@DynamoDbVersionAttribute` attached to an attribute with an `_` at the start of the name (and potentially anywhere in the name depending on parsing rules).

E.g:
``` java
@Getter
@Setter
@DynamoDbBean
public class MyDynamoObject {

    // Lombok to attach the DynamoDbEnhanced annotations
    @Getter(onMethod = @__({@DynamoDbVersionAttribute, @DynamoDbAttribute("_version")}))
    private int dynamoObjectVersion;

    private String otherFields;

    ...
}
```

### Possible Solution

Make use of `Expression.expressionNames` in a similar fashion to [`SingleKeyItemConditional`](https://github.com/aws/aws-sdk-java-v2/blob/c976d74f018081858118d26e580a6032d34d69b8/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/conditional/SingleKeyItemConditional.java#L40) within the [`VersionedRecordExtension#beforeWrite`](https://github.com/aws/aws-sdk-java-v2/blob/c976d74f018081858118d26e580a6032d34d69b8/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtension.java#L128) method.

### AWS Java SDK version used

Latest 2.0

### JDK version used

Corretto 11

### Operating System and version

AL2 Lambda

**Comment by debora-ito** [comment] 2022-07-05 21:04
@The-Zona-Zoo thank you for reaching out.
This is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/2950. Let's keep track of this in one place.

**Closed by debora-ito** 2022-07-05 21:04 UTC
Labels: bug, needs-triage
