### ISSUE TITLE
Support HEAD requests for S3Presigner

### ISSUE THREAD

**Issue by tmccombs** [aws/aws-sdk-java-v2#5473] opened 2024-08-06 19:53 UTC
### Describe the feature

S3Presigner doesn't currently seem to have any API for generating a Presigned URL for a HEAD request.

Please add a method for creating for generating such a URL. 

### Use Case

I want to generate a head request and a get request for downloading an object from s3. the client makes a head request to poll until the file to download is actually available. 

However, there doesn't currently appear to be a way to create a pre-signed s3 request for HEAD requests using the SDK v2 (there was in V1). 

### Proposed Solution

The most obvious solution would be to add a `presignHeadObject` method to the `S3Presigner` class. 

Another possibility would be to add a method to `S3Presigner` that allows you to give it any [`software.amazon.awssdk.services.s3.model.S3Request`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/S3Request.html)  and generate a signed url for it. It appears that the current implementation uses a pretty generic private method anyway.

Finally, another solution could be that S3 could allow you to use  a HEAD request with a signed GET request. See below.

### Other Information

[REFC  7231](https://datatracker.ietf.org/doc/html/rfc7231#page-25) (http/1.1) states:

> The server SHOULD send the same header fields in response to a HEAD request as it would have sent if  the request had been a GET

My interpretation of this is that  simply changing the method of a request from a GET to a HEAD shouldn't cause a request that would return 200 to return 403 instead. 

But I don't know if it is feasible for s3 to change that behavior. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.68

### JDK version used

11.0.24

### Operating System and version

Ubuntu 20.04

**Comment by debora-ito** [comment] 2024-08-06 21:04
This is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/5276.

**Closed by debora-ito** 2024-08-06 21:04 UTC
Labels: feature-request, needs-triage
