### ISSUE TITLE
Credential should be scoped to a valid region, not 'aws-global'

### ISSUE THREAD

**Issue by ilya40umov** [aws/aws-sdk-java-v2#988] opened 2019-01-02 13:49 UTC
Long story short, I'm trying to migrate a project from `software.amazon.awssdk:bom:2.0.0-preview-12` to `software.amazon.awssdk:bom:2.2.0` and the approach for picking up credentials, that used to work, now ends up failing with `SdkClientException`, which is caused by `Credential should be scoped to a valid region, not 'aws-global'` in the AwsCredentialsProviderChain.

## Context
We are using aws-okta to generate `.aws/config` / `.aws/credentials`, and it used to be enough to set `AWS_PROFILE` environment variable, to allow the application to pick up the credentials. The application in question is only using S3 client.

## Current Behavior
In `2.2.0` (and looks like this behavior started from `2.0.0-preview-13`) it's now mandatory to provide `region` in the `.aws/config`, and it does not matter if it's going to be a totally different region from the one where our S3 buckets are in. If `region` is not set on the profile, the following exception is thrown by the client:
```
Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), ProfileCredentialsProvider(profileName=..., profileFile=ProfileFile(profiles=[Profile(name=..., properties=[role_name, source_profile, role_arn]), Profile(name=..., properties=[role_name, source_profile, role_arn]), Profile(name=default, properties=[output, aws_access_key_id, aws_session_token, aws_secret_access_key])])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., ProfileCredentialsProvider(profileName=...., profileFile=ProfileFile(profiles=[Profile(name=..., properties=[role_name, source_profile, role_arn]), Profile(name=..., properties=[role_name, source_profile, role_arn]), Profile(name=default, properties=[output, aws_access_key_id, aws_session_token, aws_secret_access_key])])): Credential should be scoped to a valid region, not 'aws-global'.  (Service: Sts, Status Code: 403, Request ID: ...), ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Unable to load credentials from service endpoint.]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:112)
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:92)
	at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:70)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:54)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:51)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:62)
	at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:1597)
	at software.amazon.awssdk.services.s3.S3Client.getObject(S3Client.java:2292)
...
```

## Expected Behavior
I would expect the SDK to work the same way as aws-cli does. (E.g. I can call run `aws s3 ls --profile=... s3://...` without needing to specify the region).

## Your Environment
- `Java(TM) SE Runtime Environment (build 1.8.0_191-b12)`

**Comment by millems** [comment] 2019-01-02 22:39
**Root cause:** STS clients do not work with the AWS_GLOBAL region, which is the region that's used if no other region is found in the default credential chain. STS clients do not work with AWS_GLOBAL because STS [has no credential scope configured for the aws-global endpoint](https://github.com/aws/aws-sdk-java-v2/blob/master/core/regions/src/main/resources/software/amazon/awssdk/regions/internal/region/endpoints.json#L2303), so we fall back to aws-global for signing. aws-global is not a valid signing region.

**Repro case:**
```Java
AssumeRoleRequest assumeRoleRequest = 
        AssumeRoleRequest.builder()
                         .roleArn(ROLE_ARN)
                         .roleSessionName("aws-sdk-java-" + System.currentTimeMillis())
                         .build();

StsClient stsClient =
        StsClient.builder()
                 .region(Region.AWS_GLOBAL)
                 .credentialsProvider(() -> AwsBasicCredentials.create(userCredentials.accessKeyId(),
                                                                       userCredentials.secretAccessKey()))
                 .build();

StsAssumeRoleCredentialsProvider.builder()
                                .refreshRequest(assumeRoleRequest)
                                .stsClient(stsClient)
                                .build()
                                .resolveCredentials();
```

**Comment by millems** [comment] 2019-01-03 23:14
The referenced fix stops using `AWS_GLOBAL` as the fall-back, but does not yet fix `AWS_GLOBAL` for STS.

**Comment by millems** [comment] 2019-01-03 23:35
A fix has been made and will go out with the next release.

**Closed** 2019-01-03 23:35 UTC
Labels: Bug

**Comment by ilya40umov** [comment] 2019-01-21 13:19
@millems thanks immensely for the fix! I can confirm that the described behavior is gone in 2.3.5.

**Comment by millems** [comment] 2019-01-21 18:17
Great to hear it! Thanks for the confirmation.
