### ISSUE TITLE
Glacier Client does not send the API version

### ISSUE THREAD

**Issue by olivier-schmitt** [aws/aws-sdk-java-v2#116] opened 2017-08-21 19:26 UTC
Hello,

I'm new to AWS SDK, so I might have missed something, but here is my case.

When using Glacier Client I encountered the following exception:

**Exception in thread "main" software.amazon.awssdk.services.glacier.model.GlacierException: Required parameter missing: API version (Service: null; Status Code: 400; Error Code: null; Request ID: lYxhQ7_EeMo5MEGs3_pEX84ahaD9qpCaUH8Poat5xTOPczM)**
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:119)
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:70)
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:56)
	at software.amazon.awssdk.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
	at software.amazon.awssdk.http.pipeline.stages.ExceptionReportingStage.execute(ExceptionReportingStage.java:41)
	at software.amazon.awssdk.http.pipeline.stages.ExceptionReportingStage.execute(ExceptionReportingStage.java:30)
	at software.amazon.awssdk.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:40)
	at software.amazon.awssdk.http.pipeline.stages.TimerExceptionHandlingStage.execute(TimerExceptionHandlingStage.java:30)
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:187)
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:144)
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:78)
	at software.amazon.awssdk.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:52)
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
	at software.amazon.awssdk.http.StreamManagingStage.execute(StreamManagingStage.java:61)
	at software.amazon.awssdk.http.StreamManagingStage.execute(StreamManagingStage.java:45)
	at software.amazon.awssdk.http.pipeline.stages.AfterCallbackStage.execute(AfterCallbackStage.java:47)
	at software.amazon.awssdk.http.pipeline.stages.AfterCallbackStage.execute(AfterCallbackStage.java:35)
	at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.executeWithTimer(ClientExecutionTimedStage.java:74)
	at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:57)
	at software.amazon.awssdk.http.pipeline.stages.ClientExecutionTimedStage.execute(ClientExecutionTimedStage.java:41)
	at software.amazon.awssdk.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:203)
	at software.amazon.awssdk.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:450)
	at software.amazon.awssdk.client.ClientHandlerImpl.doInvoke(ClientHandlerImpl.java:219)
	at software.amazon.awssdk.client.ClientHandlerImpl.invoke(ClientHandlerImpl.java:201)
	at software.amazon.awssdk.client.ClientHandlerImpl.execute(ClientHandlerImpl.java:104)
	at software.amazon.awssdk.client.SdkClientHandler.execute(SdkClientHandler.java:41)
	at software.amazon.awssdk.services.glacier.DefaultGlacierClient.listVaults(DefaultGlacierClient.java:2005)

Here is my code:
```java
        GlacierClient glacierClient = GlacierClient
                .builder()
                .credentialsProvider(new EnvironmentVariableCredentialsProvider())
                .region(Region.EU_WEST_1)
                .build();
        ListVaultsRequest listVaultsRequest = ListVaultsRequest.builder()
                .build();
        ListVaultsResponse listVaultsResponse = glacierClient.listVaults(listVaultsRequest);
        List<DescribeVaultOutput> ouputs = listVaultsResponse.vaultList();
        for(DescribeVaultOutput describeVaultOutput:ouputs){
            System.out.println(describeVaultOutput.vaultARN());
        }
```
I've tested S3 client too which worked perfectly with the same API credentials.

Thanks.

**Comment by olivier-schmitt** [comment] 2017-08-22 08:01
I've built the trunk and I can notice that not a single request's generated marshaller of Glacier service uses the "apiVersion" parameter.

I don't fully understand all the code generation pipeline, some marshaller use apiVersion others don't. 

But it seems ListVaultsRequest needs that parameter and it's not added by the marshaller.

```java

    public Request<ListVaultsRequest> marshall(ListVaultsRequest listVaultsRequest) {

        if (listVaultsRequest == null) {
            throw new SdkClientException("Invalid argument passed to marshall(...)");
        }

        try {
            final ProtocolRequestMarshaller<ListVaultsRequest> protocolMarshaller = protocolFactory.createProtocolMarshaller(
                    SDK_OPERATION_BINDING, listVaultsRequest);

            protocolMarshaller.startMarshalling();
            ListVaultsRequestModelMarshaller.getInstance().marshall(listVaultsRequest, protocolMarshaller);
            return protocolMarshaller.finishMarshalling();
        } catch (Exception e) {
            throw new SdkClientException("Unable to marshall request to JSON: " + e.getMessage(), e);
        }
    }
```

When I look at EC2 generated marshaller I can see the parameter:

```java

    public Request<AllocateAddressRequest> marshall(AllocateAddressRequest allocateAddressRequest) {

        if (allocateAddressRequest == null) {
            throw new SdkClientException("Invalid argument passed to marshall(...)");
        }

        Request<AllocateAddressRequest> request = new DefaultRequest<AllocateAddressRequest>(allocateAddressRequest, "EC2Client");
        request.addParameter("Action", "AllocateAddress");
        request.addParameter("Version", "2016-11-15");
        request.setHttpMethod(HttpMethodName.POST);

        if (allocateAddressRequest.domain() != null) {
            request.addParameter("Domain", StringUtils.fromString(allocateAddressRequest.domain()));
        }

        return request;
    }
```
Thx for your help.

**Comment by shorea** [comment] 2017-08-22 14:32
Thanks for reporting! Looks like this is a regression, I've submitted a fix for PR, https://github.com/aws/aws-sdk-java-v2/pull/117

**Comment by dagnir** [comment] 2017-08-22 17:08
Fixed in https://github.com/aws/aws-sdk-java-v2/commit/0340c02d02427605da122028e6a04e0f3696c87f

**Closed by dagnir** 2017-08-22 17:08 UTC
Labels: Bug
