### ISSUE TITLE
IoT: Thread hangs when trying to create a thing

### ISSUE THREAD

**Issue by jonyt** [aws/aws-sdk-java-v2#2127] opened 2020-10-29 20:33 UTC
I'm trying to create a thing, but the thread that's doing it hangs. No error messages or anything else. This happens only in one environment. The exact same code runs successfully in 3 other environments. The relevant environment variables seem ok in all environments. I tried enabling the crt log but no log file is created, perhaps because there are no crt log statements for the code I'm running. My code and logs are below, any ideas on how to debug this?

Logs
```
2020-10-29 16:16:51,533 main DEBUG [sysaid] [SysAid Server] com.ilient - Creating policy {"Version":"2012-10-17","Id":"inst05us-app02-2051","Statement":[{"Sid":"1","Effect":"Allow","Action":["iot:Publish"],"Resource":["arn:aws:iot:us-east-1:1234:topic/*"]},{"Sid":"2","Effect":"Allow","Action":["iot:Subscribe"],"Resource":["arn:aws:iot:us-east-1:1234:topicfilter/*"]},{"Sid":"3","Effect":"Allow","Action":["iot:Connect"],"Resource":["arn:aws:iot:us-east-1:1234client/inst05us-app02-2051"],"Condition":{"ForAllValues:StringEquals":{"iot:ConnectAttributes":["PersistentConnect"]}}}]}
2020-10-29 16:16:51,549 main DEBUG [sysaid] [] awssdk.core.interceptor.ExecutionInterceptorChain - Creating an interceptor chain that will apply interceptors in the following order: [software.amazon.awssdk.awscore.interceptor.HelpfulUnknownHostExceptionInterceptor@f0fdbd9]
2020-10-29 16:16:51,551 main DEBUG [sysaid] [] software.amazon.awssdk.request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=iot.us-east-1.amazonaws.com, encodedPath=/policies/inst05us-app02-2051, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent], queryParameters=[])
2020-10-29 16:16:51,552 main DEBUG [sysaid] [] awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20201029T201651Z
20201029/us-east-1/execute-api/aws4_request
d941d0ae05dc9748a1553d0deb91d7f5282ce3093c9cc73cec1e1a36566b0b27
```

Code:
```
AwsCredentialsProvider credentialsProvider = AwsCredentialsProviderChain.of(InstanceProfileCredentialsProvider.create(), EnvironmentVariableCredentialsProvider.create());
AwsRegionProvider regionProvider = new AwsRegionProviderChain(new SystemSettingsRegionProvider(), new InstanceProfileRegionProvider());

IotAsyncClient client = IotAsyncClient.builder()
                .region(regionProvider.getRegion())
                .credentialsProvider(credentialsProvider)
                .build();
AttributePayload attributePayload = AttributePayload.builder().attributes(Collections.singletonMap("accountId", accountId)).build();
CreateThingRequest createThingRequest = CreateThingRequest.builder().thingName(iotDeviceId).attributePayload(attributePayload).build();
CompletableFuture<CreateThingResponse> createThingFuture = client.createThing(createThingRequest);
String policyDocument = createPolicy(iotDeviceId, deviceType, TopicSupplier.getTopicBase(accountId, deviceId));
logger.debug("Creating policy {}", policyDocument);
CreatePolicyRequest createPolicyRequest = CreatePolicyRequest.builder().policyName(iotDeviceId).policyDocument(policyDocument).build();
CompletableFuture<CreatePolicyResponse> createPolicyFuture = client.createPolicy(createPolicyRequest);


try {
	createThingFuture
		.thenCombine(createPolicyFuture, (createThingResponse, createPolicyResponse) -> createThingResponse)
		.join();
} catch (ExecutionException | InterruptedException e) {
}
```

## Your Environment
* AWS Java SDK version used: 2.13.54
* JDK version used: 1.8.0_181-b13
* Operating System and version: Amazon Linux AMI 2016.03

**Comment by zoewangg** [comment] 2020-10-29 21:42
Hi @jonyt, when you say `crt`, do you mean AWS CRT HTTP client? or you are using Netty HTTP client(the default async client)? Did this start recently with a package or code update, or has it always happened?

**Comment by jonyt** [comment] 2020-10-30 06:12
Hi Zoe, I'm using the default client. I didn't update anything. As I
mentioned the same code works perfectly on other servers. It's almost
certainly an environment issue, since this is our only server in us-east-1,
but I'm not sure how to debug this since I can't tell what the SDK is stuck
on. A thread dump I took says it's the thing creation but that's the only
info I have.

**Comment by zoewangg** [comment] 2020-10-30 21:44
I see. Could you share the thread dump? Event loop threads (name prefix: `aws-java-sdk-NettyEventLoop`) and SDK response completion threads (name prefix`sdk-async-response`) should be sufficient. 

For Netty HTTP client, you can enable wirelogs by setting the log level for `io.netty.handler.logging.LoggingHandler`
eg:
```
log4j.logger.io.netty.handler.logging.LoggingHandler=DEBUG
```

**Comment by jonyt** [comment] 2020-10-31 19:30
Thread dump:
```
"aws-java-sdk-NettyEventLoop-1-3" #62 daemon prio=5 os_prio=0 tid=0x00007f0a3804a000 nid=0x3b85 waiting on condition [0x00007f0a47c7b000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.channel.nio.NioEventLoop.handleLoopException(NioEventLoop.java:568)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:519)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

"aws-java-sdk-NettyEventLoop-1-2" #61 daemon prio=5 os_prio=0 tid=0x00007f0a6a317800 nid=0x3b84 waiting on condition [0x00007f0a47cfc000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.channel.nio.NioEventLoop.handleLoopException(NioEventLoop.java:568)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:519)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

"aws-java-sdk-NettyEventLoop-1-1" #60 daemon prio=5 os_prio=0 tid=0x00007f0a6a303800 nid=0x3b83 waiting on condition [0x00007f0a47d7d000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.channel.nio.NioEventLoop.handleLoopException(NioEventLoop.java:568)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:519)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

"aws-java-sdk-NettyEventLoop-1-0" #59 daemon prio=5 os_prio=0 tid=0x00007f0a6a301800 nid=0x3b82 waiting on condition [0x00007f0a47dfe000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at io.netty.channel.nio.NioEventLoop.handleLoopException(NioEventLoop.java:568)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:519)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

Logs:
```
2020-10-31 15:08:55,753 main DEBUG  org.apache.http.wire - http-outgoing-0 >> "GET /repository/AmazonRootCA1.pem HTTP/1.1[\r][\n]"
2020-10-31 15:08:55,753 main DEBUG  org.apache.http.wire - http-outgoing-0 >> "Host: www.amazontrust.com[\r][\n]"
2020-10-31 15:08:55,753 main DEBUG  org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2020-10-31 15:08:55,753 main DEBUG  org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.12 (Java/1.8.0_181)[\r][\n]"
2020-10-31 15:08:55,753 main DEBUG  org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020-10-31 15:08:55,753 main DEBUG  org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Content-Type: text/plain; charset=US-ASCII[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Content-Length: 1188[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Date: Mon, 21 Sep 2020 05:21:48 GMT[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Cache-Control: max-age=31556952, public[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Last-Modified: Wed, 15 Apr 2020 20:24:22 GMT[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "x-amz-version-id: EI6D7Vy6ZfxLsvS05WgR3cV1XOZWi5bP[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "ETag: "7095142f080d1d25221eec161ff14223"[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Server: AmazonS3[\r][\n]"
2020-10-31 15:08:55,755 main DEBUG  org.apache.http.wire - http-outgoing-0 << "X-Cache: Hit from cloudfront[\r][\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Via: 1.1 c242c974a465288488c7876cabca7752.cloudfront.net (CloudFront)[\r][\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "X-Amz-Cf-Pop: IAD89-C2[\r][\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "X-Amz-Cf-Id: 8RgQR1S3nrD8R8S_Ad8-3G3meDFNbEiEVNGQpJbTRZHNwX5-FnYRbw==[\r][\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "Age: 3505628[\r][\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "-----BEGIN CERTIFICATE-----[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "rqXRfboQnoZsG4q5WTP468SQvvG5[\n]"
2020-10-31 15:08:55,756 main DEBUG  org.apache.http.wire - http-outgoing-0 << "-----END CERTIFICATE-----[\n]"
2020-10-31 15:08:56,819 main DEBUG  awssdk.regions.providers.AwsRegionProviderChain - Unable to load region from software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@54e3c8c2:Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region).
2020-10-31 15:08:57,044 main DEBUG - Creating certificate issuer in region us-east-1
2020-10-31 15:08:57,083 main DEBUG  awssdk.regions.providers.AwsRegionProviderChain - Unable to load region from software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@54e3c8c2:Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region).
2020-10-31 15:08:58,049 main DEBUG  awssdk.auth.credentials.AwsCredentialsProviderChain - Loading credentials from InstanceProfileCredentialsProvider()
2020-10-31 15:08:58,054 main DEBUG  awssdk.core.interceptor.ExecutionInterceptorChain - Creating an interceptor chain that will apply interceptors in the following order: [software.amazon.awssdk.awscore.interceptor.HelpfulUnknownHostExceptionInterceptor@630ca940]
2020-10-31 15:08:58,191 main DEBUG  software.amazon.awssdk.request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=iot.us-east-1.amazonaws.com, encodedPath=/things/test-device, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent], queryParameters=[])
2020-10-31 15:08:58,199 main DEBUG  awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20201031T190858Z
20201031/us-east-1/execute-api/aws4_request
cc868bc0d54ac19780600b4e8bd63af3d3c3f2f144cce5fd63c2c9697d3d347d
2020-10-31 15:08:58,460 main DEBUG [sysaid] [SysAid Server] com.ilient - Creating policy {"Version":"2012-10-17","Id":"test-device","Statement":[{"Sid":"1","Effect":"Allow","Action":["iot:Publish"],"Resource":["arn:aws:iot:us-east-1:12345678:topic/*"]},{"Sid":"2","Effect":"Allow","Action":["iot:Subscribe"],"Resource":["arn:aws:iot:us-east-1:12345678:topicfilter/*"]},{"Sid":"3","Effect":"Allow","Action":["iot:Connect"],"Resource":["arn:aws:iot:us-east-1:12345678:client/test-device"],"Condition":{"ForAllValues:StringEquals":{"iot:ConnectAttributes":["PersistentConnect"]}}}]}
2020-10-31 15:08:58,477 main DEBUG  awssdk.core.interceptor.ExecutionInterceptorChain - Creating an interceptor chain that will apply interceptors in the following order: [software.amazon.awssdk.awscore.interceptor.HelpfulUnknownHostExceptionInterceptor@630ca940]
2020-10-31 15:08:58,478 main DEBUG  software.amazon.awssdk.request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=iot.us-east-1.amazonaws.com, encodedPath=/policies/test-device, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent], queryParameters=[])
2020-10-31 15:08:58,479 main DEBUG  awssdk.auth.signer.Aws4Signer - AWS4 String to sign: AWS4-HMAC-SHA256
20201031T190858Z
20201031/us-east-1/execute-api/aws4_request
8bd0e2f9037fb46d678a4cba2a3569e19abf95f480e8918105cbf8337e174115
```

**Comment by debora-ito** [comment] 2020-11-24 01:01
@jonyt I see your ticket with Premium Support was resolved, so I'll go ahead and close this issue.

The root cause was dependency issues/conflicts in the deployment environment.

**Closed by debora-ito** 2020-11-24 01:01 UTC
Labels: bug
