### ISSUE TITLE
Whitespace in ~/.aws/config throws exception after updating to AWS SDK v2 

### ISSUE THREAD

**Issue by reshma-td** [aws/aws-sdk-java-v2#2248] opened 2021-01-20 13:41 UTC
## Describe the bug
After updating to AWS SDK v2, `~/.aws/config` throws exception because of whitespace in the file.

## Expected Behavior
Exception should not be thrown when there is whitespace in `~/.aws/config`

## Current Behavior

```
java.lang.IllegalArgumentException: Expected an '=' sign defining a property on line 4

	at software.amazon.awssdk.utils.Validate.isTrue(Validate.java:76)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.parsePropertyDefinition(ProfileFileReader.java:250)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.readPropertyDefinitionLine(ProfileFileReader.java:132)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.parseLine(ProfileFileReader.java:78)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.lambda$parseFile$0(ProfileFileReader.java:58)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.parseFile(ProfileFileReader.java:58)
	at software.amazon.awssdk.profiles.ProfileFile$BuilderImpl.build(ProfileFile.java:265)
	at software.amazon.awssdk.profiles.ProfileFile.lambda$addConfigFile$1(ProfileFile.java:150)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at software.amazon.awssdk.profiles.ProfileFile.addConfigFile(ProfileFile.java:147)
	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
	at software.amazon.awssdk.profiles.ProfileFile.defaultProfileFile(ProfileFile.java:91)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.mergeGlobalDefaults(SdkDefaultClientBuilder.java:201)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:154)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:27)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:129)
```

## Steps to Reproduce
In `~/.aws/config` , add a newline with whitespace between two profiles.

```
[default]
region = eu-west-1
output = json
 
[profile id-dev]
role_arn = arn:aws:iam::7...7:role/XXXX
source_profile = default
mfa_serial=arn:aws:iam::3...3:mfa/xxx
```

## Your Environment
* AWS Java SDK version used: 2.15.60
* JDK version used: openjdk 15.0.1
* Operating System and version: macOS Big Sur 11.1

**Comment by debora-ito** [comment] 2021-01-20 18:10
@reshma-td Weird, my `~/.aws/config` is similar to yours but I don't see this issue.
Can you provide a reproducible code?

**Comment by reshma-td** [comment] 2021-01-21 09:50
@debora-ito 

Did you add a whitespace in the newline between the profiles ? Can you see below, I have added a whitespace in the newline.
Its hard to notice :)

> [default]
> region = eu-west-1
> output = json
> ` `
> [profile id-dev]
> role_arn = arn:aws:iam::7...7:role/XXXX
> source_profile = default
> mfa_serial=arn:aws:iam::3...3:mfa/xxx

Here is a sample code that could reproduce the issue.

```
  public void test() {

    final var path = "~/.aws/config".replaceFirst("^~", System.getProperty("user.home"));
    final var inputStream = FunctionalUtils.invokeSafely(
        () -> Files.newInputStream(Path.of(path)));

    final var type = ProfileFile.Type.CONFIGURATION;

    ProfileFileReader.parseFile(inputStream, type);

  }
```

**Comment by debora-ito** [comment] 2021-02-18 02:54
Sorry about the delayed response. I still cannot reproduce it.

The ProfileFileReader should skip empty lines, which are defined by a Pattern:
 
https://github.com/aws/aws-sdk-java-v2/blob/d60231e40103ef6c04a3b5d1b231640c8ec0ee44/core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java#L43

Any idea how the whitespace is being added? It was by updating the config file manually or using the aws cli?

**Comment by reshma-td** [comment] 2021-02-25 08:15
Sorry for the delayed response. I manually added the whitespace in config file.

I was trying to reproduce it now again but I could not.
I could when I created this ticket. :)

**Comment by debora-ito** [comment] 2021-02-25 19:38
Well I'm glad you're not blocked by this anymore. I'll go ahead and close this then, feel free to reopen if you experience it again.

**Closed by debora-ito** 2021-02-25 19:38 UTC
Labels: bug
