### ISSUE TITLE
CloudWatch Logs PutRetention cannot set never expire

### ISSUE THREAD

**Issue by mobsense** [aws/aws-sdk-java-v2#2590] opened 2021-07-13 03:17 UTC
The PutRetention API is meant to accept only a logGroupName and the retentionInDays is meant to be optional. However the SDK has retentionInDays as a required parameter.

## Describe the bug
Put retention is requiring a retentionInDays. The doc: https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html. says that omitting the retentionInDays should set the log group to never expire. However, The SDK v2 requires this parameter so you can never set a log group to never expire.

## Expected Behavior
The API PutRetention without a retentionInDays should succeed.
```
{
    "logGroupName": "name"
}
```
## Current Behavior
Get this message:

```
MissingRequiredParameter: Missing required key 'retentionInDays' in params
    at ParamValidator.fail (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (webpack-internal:///./node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (webpack-internal:///./node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (webpack-internal:///./node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at eval (webpack-internal:///./node_modules/aws-sdk/lib/event_listeners.js:86:9)
    at finish (webpack-internal:///./node_modules/aws-sdk/lib/config.js:386:7)
    at eval (webpack-internal:///./node_modules/aws-sdk/lib/config.js:404:9)
```

## Possible Solution
The parameter should not be marked in the SDK as required.

## Context
Trying to set via API log groups back to never expire. Cannot be done programatically.

## Your Environment

* Browser based SDK on a mac

**Comment by debora-ito** [comment] 2021-07-13 21:31
Hi @mobsense can you elaborate on the environment you're using? It doesn't look like it's using Java but I'm curious about it.

Regardless of the environment, I think there's some confusion in the documentation and in the API validation. Quoting the API Reference:

> retentionInDays
The number of days to retain the log events in the specified log group. Possible values are: 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, and 3653.
>
>If you omit retentionInDays in a PutRetentionPolicy operation, the events in the log group are always retained and never expire.
>
>Type: Integer
>Required: Yes

How can I omit retentionInDays if it's a required parameter? 

This validation is being made on the service side, so I'll reach out to the CloudwatchLogs team to clarify if this is the intended behavior. Will update here what I hear back.

**Comment by mobsense** [comment] 2021-07-14 02:00
I'm using Node 14.x with the current SDK. Tried earlier versions too. 

The workaround the console appears to be doing is to call DeleteRetentionPolicy which is a work-around.

**Comment by debora-ito** [comment] 2021-07-27 17:21
@mobsense The Cloudwatch Logs team responded, and they confirmed that DeleteRetentionPolicy is in fact the correct operation to call when you want the policy to never expire.

They have updated the API Reference with this new info - 
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html

Closing this. Please reach out if you have other questions.

**Closed by debora-ito** 2021-07-27 17:21 UTC
Labels: bug, service-api

**Comment by mobsense** [comment] 2021-07-27 20:44
Thank you. The doc update clarifies it.
