### ISSUE TITLE
InitiateAuthRequest toString() will log sensitive data in the clear 

### ISSUE THREAD

**Issue by richhart** [aws/aws-sdk-java-v2#1333] opened 2019-07-09 09:38 UTC
When creating an `InitiateAuthRequest` from the `CognitoIdentityProviderRequest` class the authParameters can contain sensitive information i.e. secret / password. When logging this output the sensitive data can be exposed to the output logs. For example:

Creating an auth request with user/password auth flow:
`final InitiateAuthRequest request = InitiateAuthRequest.builder().authFlow(AuthFlowType.USER_PASSWORD_AUTH)
                .clientId("clientId")
                .authParameters(ImmutableMap.of(USERNAME, "username", PWORD, "passwordInClear")).build();
`
when logging the line above:
`LOG.debug("InitiateAuthRequest [{}]", request);`

the output results in:
`InitiateAuthRequest [InitiateAuthRequest(AuthFlow=USER_PASSWORD_AUTH, AuthParameters={PASSWORD=passwordInClear, USERNAME=username}, ClientMetadata=software.amazon.awssdk.core.util.DefaultSdkAutoConstructMap@448ff1a8, ClientId=** Sensitive Data Redacted **)]`

I believe the AuthParameters should also be made sensitive or at least partially sensitive for certain keys like the ClientId is.

**Comment by debora-ito** [comment] 2019-07-09 22:16
Transferred issue to V2 repo.

**Comment by dagnir** [comment] 2019-07-10 22:23
Hi @richhart, this is something that needs to be modeled in the service model, which is maintained by the Cognito IDP team. At the moment, the `AuthParameters` type is [modeled as a map from string to string](https://github.com/aws/aws-sdk-java-v2/blob/5a799393ce9f34b07625ca5d614e5f6367ec7780/services/cognitoidentityprovider/src/main/resources/codegen-resources/service-2.json#L3140-L3144) which is why they're not redacted. I've reached out to the Cognito IDP team and provided them a link to this issue to see what can be done about this.

**Comment by dagnir** [comment] 2020-02-12 00:44
Hi @richhart, it looks like the request parameter was updated today to be marked as sensitive: https://github.com/aws/aws-sdk-java-v2/blob/c55ca9140a4d69ccae2dfa9992b3f626513b3994/services/cognitoidentityprovider/src/main/resources/codegen-resources/service-2.json#L3187-L3195

Can you please check to see if this fixes the issue?

**Comment by debora-ito** [comment] 2020-02-18 18:57
I checked, the code sample output now shows:
```
InitiateAuthRequest(AuthFlow=USER_PASSWORD_AUTH, AuthParameters=*** Sensitive Data Redacted ***, ClientMetadata={}, ClientId=*** Sensitive Data Redacted ***)
```

So the issue is resolved. Feel free to reopen if you have any further questions.

**Closed by debora-ito** 2020-02-18 18:57 UTC
Labels: pending-verification, service-api
