### ISSUE TITLE
S3 ListObjectsV2Request throws WstxParsingException

### ISSUE THREAD

**Issue by er1c** [aws/aws-sdk-java-v2#1172] opened 2019-03-28 17:30 UTC
While doing some edge-case testing for various S3 key object names, I am triggering an XML parsing exception from the `aws-sdk-java-v2` API.

Example List Request:

```
ListObjectsV2Request(Bucket=XXXX, Delimiter=/, MaxKeys=100, Prefix=AzyKoWCh9tXQYtXSCcJc8/)
```

Bucket Contents for `AzyKoWCh9tXQYtXSCcJc8/`: 

Netty Debug:

```
10:05:14.127 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] WRITE: software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor$StreamedRequest(DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
GET https://s3.us-west-2.amazonaws.com/XXXX?list-type=2&delimiter=%2F&max-keys=100&prefix=AzyKoWCh9tXQYtXSCcJc8%2F HTTP/1.1
amz-sdk-invocation-id: 65dbff5a-eea0-50eb-6dfd-02b6ab04ee15
amz-sdk-retry: 0/0/500
Authorization: AWS4-HMAC-SHA256 Credential.....
Host: s3.us-west-2.amazonaws.com
User-Agent: aws-sdk-java/2.5.10 Mac_OS_X/10.14.4 Java_HotSpot_TM__64-Bit_Server_VM/11.0.2+9-LTS Java/11.0.2 scala/2.12.8
x-amz-content-sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20190328T170514Z)
10:05:14.128 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] FLUSH
10:05:14.131 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] FLUSH
10:05:14.132 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] WRITE, DefaultHttpContent(data: PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 0), decoderResult: success), 0B
10:05:14.132 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] FLUSH
10:05:14.133 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
10:05:14.135 [aws-java-sdk-NettyEventLoop-1-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xa8b5a6ca, L:/10.235.235.245:55209 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
10:05:14.136 [aws-java-sdk-NettyEventLoop-1-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xa8b5a6ca, L:/10.235.235.245:55209 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
10:05:14.137 [aws-java-sdk-NettyEventLoop-1-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xa8b5a6ca, L:/10.235.235.245:55209 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
10:05:14.138 [aws-java-sdk-NettyEventLoop-1-1] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xa8b5a6ca, L:/10.235.235.245:55209 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
10:05:14.138 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
10:05:14.148 [aws-java-sdk-NettyEventLoop-1-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
10:05:14.148 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] USER_EVENT: SslHandshakeCompletionEvent(SUCCESS)
10:05:14.149 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] WRITE, EmptyLastHttpContent, 0B
10:05:14.149 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] FLUSH
10:05:14.150 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
10:05:14.194 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
x-amz-id-2: rozpAproTn/BpZvKyaMPes22k/UAr7owWBpoa0iHyCCtJ6kLl4VTLNganyb9r63SWVUFvp9rkcI=
x-amz-request-id: EF80987337552DF0
Date: Thu, 28 Mar 2019 17:05:15 GMT
x-amz-bucket-region: us-west-2
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3
10:05:14.205 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
...
10:05:14.211 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ, EmptyLastHttpContent, 0B
10:05:14.234 [aws-java-sdk-NettyEventLoop-1-3] DEBUG i.n.handler.logging.LoggingHandler - [id: 0xf0a821a3, L:/10.235.235.245:55210 - R:s3.us-west-2.amazonaws.com/54.231.177.4:443] READ COMPLETE
10:05:14.242 [scala-execution-context-global-45] ERROR t.w.w.v.WebCat30AdminWSServerFactoryImpl - Caught Exception
java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Could not parse XML response.
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
```

```
Caused by: com.ctc.wstx.exc.WstxParsingException: Illegal character entity: expansion character (code 0x8
 at [row,col {unknown-source}]: [2,1704]
```

I extracted the response XML Raw:

```
<?xml version="1.0" encoding="UTF-8"?>.<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>XXXXX</Name><Prefix>AzyKoWCh9tXQYtXSCcJc8/</Prefix><KeyCount>17</KeyCount><MaxKeys>100</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>AzyKoWCh9tXQYtXSCcJc8/config.json</Key><LastModified>2019-03-25T16:58:51.000Z</LastModified><ETag>&quot;add7403b95c4164509110b1eac281ae6&quot;</ETag><Size>22</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>AzyKoWCh9tXQYtXSCcJc8/config2.json</Key><LastModified>2019-03-25T17:09:15.000Z</LastModified><ETag>&quot;dc11509244e7c8cdff513abeb8cb932c&quot;</ETag><Size>576</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>AzyKoWCh9tXQYtXSCcJc8/config23.json</Key><LastModified>2019-03-27T13:39:18.000Z</LastModified><ETag>&quot;dc11509244e7c8cdff513abeb8cb932c&quot;</ETag><Size>576</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>AzyKoWCh9tXQYtXSCcJc8/config231.json</Key><LastModified>2019-03-27T13:45:01.000Z</LastModified><ETag>&quot;dc11509244e7c8cdff513abeb8cb932c&quot;</ETag><Size>576</Size><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>AzyKoWCh9tXQYtXSCcJc8/config2_mvo.json</Key><LastModified>2019-03-28T16:50:42.000Z</LastModified><ETag>&quot;9af7c117d9de9a06fba7a5f1ea5fcc2d&quot;</ETag><Size>1</Size><StorageClass>STANDARD</StorageClass></Contents><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/%a%b%/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/&amp;#9986;/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/&amp;#9986;.../</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/a&#x8;/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/a  b/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/a b/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/a&amp;$@=;:+ ,?/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/a&amp;b/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/a/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/ab/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/asdf/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>AzyKoWCh9tXQYtXSCcJc8/...&amp;#9986;.../</Prefix></CommonPrefixes></ListBucketResult>
```

Formatted:

```
<?xml version="1.0" encoding="UTF-8"?>.
<ListBucketResult
    xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>XXXX</Name>
    <Prefix>AzyKoWCh9tXQYtXSCcJc8/</Prefix>
    <KeyCount>17</KeyCount>
    <MaxKeys>100</MaxKeys>
    <Delimiter>/</Delimiter>
    <IsTruncated>false</IsTruncated>
    <Contents>
        <Key>AzyKoWCh9tXQYtXSCcJc8/config.json</Key>
        <LastModified>2019-03-25T16:58:51.000Z</LastModified>
        <ETag>&quot;add7403b95c4164509110b1eac281ae6&quot;</ETag>
        <Size>22</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
    <Contents>
        <Key>AzyKoWCh9tXQYtXSCcJc8/config2.json</Key>
        <LastModified>2019-03-25T17:09:15.000Z</LastModified>
        <ETag>&quot;dc11509244e7c8cdff513abeb8cb932c&quot;</ETag>
        <Size>576</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
    <Contents>
        <Key>AzyKoWCh9tXQYtXSCcJc8/config23.json</Key>
        <LastModified>2019-03-27T13:39:18.000Z</LastModified>
        <ETag>&quot;dc11509244e7c8cdff513abeb8cb932c&quot;</ETag>
        <Size>576</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
    <Contents>
        <Key>AzyKoWCh9tXQYtXSCcJc8/config231.json</Key>
        <LastModified>2019-03-27T13:45:01.000Z</LastModified>
        <ETag>&quot;dc11509244e7c8cdff513abeb8cb932c&quot;</ETag>
        <Size>576</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
    <Contents>
        <Key>AzyKoWCh9tXQYtXSCcJc8/config2_mvo.json</Key>
        <LastModified>2019-03-28T16:50:42.000Z</LastModified>
        <ETag>&quot;9af7c117d9de9a06fba7a5f1ea5fcc2d&quot;</ETag>
        <Size>1</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/%a%b%/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/&amp;#9986;/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/&amp;#9986;.../</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/a&#x8;/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/a  b/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/a b/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/a&amp;$@=;:+ ,?/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/a&amp;b/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/a/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/ab/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/asdf/</Prefix>
    </CommonPrefixes>
    <CommonPrefixes>
        <Prefix>AzyKoWCh9tXQYtXSCcJc8/...&amp;#9986;.../</Prefix>
    </CommonPrefixes>
</ListBucketResult>
```

I believe the bug is in parsing: `<Prefix>AzyKoWCh9tXQYtXSCcJc8/a&#x8;/</Prefix>`.

This isn't a valid XML-escaped field.

It should be:

`<Prefix>AzyKoWCh9tXQYtXSCcJc8/a&amp;#x8;/</Prefix> `

I guess I don't know if this is a bug in the client, or if the S3 server response is simply not properly encoding the '&' character in the xml value.

It's also broken in the S3 Console too:

Either way, how do I best report this?

**Comment by zoewangg** [comment] 2019-03-28 19:15
Hi @er1c I edited your description and removed the bucket names for security reasons. 
Investigating the issue

**Comment by er1c** [comment] 2019-03-28 19:34
Thanks, they do not have public access enabled.  Will be interesting to hear what you find out.

**Comment by zoewangg** [comment] 2019-03-28 20:32
Yeah, the root cause is that `&` is not correctly escaped.

How did you upload the object using key `a&#x8;` in the first place? Did you use the same java sdk? I tried to upload an object using the same key with v2 s3 client and then called `s3.listObjectsV2` and it was working. I verified `&` in the response payload was correctly escaped.

**Comment by er1c** [comment] 2019-03-28 20:35
Yes, I used the same java sdk, but with a quirk.

Effectively just:

```
    val putRequestBuilder: PutObjectRequest.Builder = PutObjectRequest.builder()
      .bucket(bucketName)
      .key(java.net.URLEncoder.encode(bucketFilePath))
```

**Comment by zoewangg** [comment] 2019-04-02 17:42
Can you try specifying encodingType in your `ListObjectsV2Request`?

```
        ListObjectsV2Response result = s3.listObjectsV2(ListObjectsV2Request.builder()
                                                                            .bucket(bucketName)
                                                                            .prefix(prefix)
                                                                            .encodingType(encodingType)
                                                                            .build());
```

**Comment by er1c** [comment] 2019-04-02 17:54
I understand this is a weird edge case, but isn't it still a bug that the S3 Service can return a non-properly escaped XML field?  To be clear, this isn't really a blocker for me, I don't actually intend to use the extended characters, so if you want to close this issue, that's fine.  I put some more strict ascii-only characters in my implementation for now.

**Comment by dagnir** [comment] 2019-09-20 21:04
I think the reasoning behind this is that S3 doesn't want to modify the object keys unless instructed to so they are added as-is to the response XML. As @zoewangg noted, if there is a possibility that the keys contain characters that are out of range, the request should including the `encodingType` property.

Per the latest comment by @er1c going to go ahead and close this. Feel free to reopen if you have further questions or concerns.

**Closed by dagnir** 2019-09-20 21:04 UTC
Labels: investigating
