### ISSUE TITLE
S3 virtual-style addressing for non AWS endpoints

### ISSUE THREAD

**Issue by ebabani** [aws/aws-sdk-java-v2#722] opened 2018-09-23 23:59 UTC
Any consideration to allowing DNS style bucked addresses for non s3 endpoints?

## Expected Behavior
Expect virtual style addressing to work for non-s3 endpoints as well.

## Current Behavior
Currently DNS style addressing is only enabled if the endpoint starts with s3. (https://github.com/aws/aws-sdk-java-v2/blob/1203086f21355a1fba45d4f0119b090cb3d77995/services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java#L141) 

There are s3 compatible providers that support only DNS style addressing, which makes this SDK harder to use with them. (https://www.alibabacloud.com/help/doc-detail/64919.htm)

## Possible Solution
Remove the restriction on DNS style addresses only working for the AWS s3 endpoints. 

## Context
Trying to use this client on Alicloud OSS.

## Your Environment
<N/A>

**Comment by ebabani** [comment] 2018-09-30 23:50
The change is fairly straight forward to make, but just want to know what the direction is regarding this. At the moment if feels like for s3 compatible providers this sdk leans towards forcing the path style.

**Comment by millems** [comment] 2018-10-01 17:48
It's tough for us to test to make sure we're compatible with all of them, but we're definitely not against it. We'd gladly accept a PR that fixes the issue.

**Comment by blackstorm** [comment] 2020-05-27 09:04
i decide back to sdk v1. Sad!

**Comment by millems** [comment] 2020-05-27 17:23
Note: This feature request is just a convenience. You can always enable virtual-style addressing manually:

```java
S3Client.builder()
        .serviceConfiguration(c -> c.pathStyleAccessEnabled(true))
        .build();
```

We don't consider this a blocker to moving to V2, so it's not high on our priorities.

**Comment by yannrouillard** [comment] 2020-10-16 15:30
Currently experiencing this issue as well.

@millems I saw you were not keen to merge the PR https://github.com/aws/aws-sdk-java-v2/pull/763, is there some other way to make it work that you would accept like creating a new option to force virtual-style addressing?

**Comment by millems** [comment] 2020-10-16 18:43
It's going to be difficult to figure out how to support this, with new features like [S3 access points](https://aws.amazon.com/s3/features/access-points/) adding even more complexity to the URL building process, and the S3 specification being implemented differently by different providers.

Is there a specific non-AWS runtime we can focus in on supporting, so that we don't just have it be "all non-AWS S3 implementations"?

**Comment by yannrouillard** [comment] 2020-10-20 19:55
Hi @millems,

I am not sure I am legimitate to say which non-AWS runtime should be better to focus on.
You could target Google / Alicloud implementations to facilite migrations from them to AWS but I would find weird that you have to follow Google / Alicloud modifications to stay compatible (and pay some complexities price on the way).
_(In our case it is with Alicloud implementation that we have an issue with using this library)_

Supporting an alternate implementation like Minio sounds better as it is an open-source project and can be used by people to use S3-like interfaces on-premise in hybrid configuration (or for testing purpose).

In the end anyway, I don't see how you can maintain compatibility with existing behaviour without introducing a new option or a new configuration.

I saw you were refactoring to separate between `accessPointEndpointResolver` and `bucketEndointResolver`, maybe you could allow to set a custom resolver so that library users have always a way to customize / override behavior like this without incurring too high maintainance on your side.

In all cases, it would be nice to document this behaviour (_virtualAccesStyle can't be enabled for endpoints that do not begin by `s3`) in the official documentation to avoid the surprise effect. Other SDK don't have this behaviour AFAIK so it took us some time to find the cause.

**Closed** 2022-11-14 14:43 UTC
Labels: feature-request
