### ISSUE TITLE
SQS ReceiveMessageRequest attributeNames() are not Message Attributes

### ISSUE THREAD

**Issue by WillyGitty** [aws/aws-sdk-java-v2#2615] opened 2021-07-21 23:01 UTC
## Describe the bug

In SQS,  ReceiveMessageRequest.builder().attributeNames() Enum values does not correspond the the message attributes

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/ReceiveMessageRequest.html
 
- All
- ApproximateFirstReceiveTimestamp
- ApproximateReceiveCount
- AWSTraceHeader
- SenderId
- SentTimestamp
- MessageDeduplicationId
- MessageGroupId
- SequenceNumber

Right now the method accepts the QueueAttributeName enum that does not contains those values.

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/QueueAttributeName.html

## Expected Behavior

When trying to receive message with some specific attributes I should be able to specify them using the correct Enum.

## Current Behavior

The method attributeNames() should use an Enum with message attributes values (ex: MessageAttributeNames) 

## Steps to Reproduce

For example, now since the attributeNames is scoped to the wrong enum, we cant get a property like _ApproximateReceiveCount_
```java
        final ReceiveMessageRequest receiveMessageRequest = ReceiveMessageRequest.builder()
            .queueUrl(queueUrl)
            // I cant call an enum with the ApproximateReceiveCount
            .attributeNames(QueueAttributeName.???) 
            // However this works
            .attributeNamesWithStrings("ApproximateReceiveCount")
            .maxNumberOfMessages(10)
            .waitTimeSeconds(seconds)
            .build();
```
As you can see `.attributeNamesWithStrings("ApproximateReceiveCount")` does behave correctly but It is impossible to do the same with the Enum version  `.attributeNames(???)`.

## Possible Solution

Implement a new enum (ex: MessageAttributeNames)
that coincide with the following properties

- All
- ApproximateFirstReceiveTimestamp
- ApproximateReceiveCountAWSTraceHeader
- SenderId
- SentTimestamp
- MessageDeduplicationId
- MessageGroupId
- SequenceNumber

## Your Environment

* AWS Java SDK version used: 2.17.1
* JDK version used: openjdk 11
* Operating System and version: Linux with Ubuntu 20.04 LTS

**Comment by debora-ito** [comment] 2021-07-23 01:29
Hi @WillyGitty this is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/1117.

We have reached out to the service team about this, they are aware of the problem and working on a plan to fix this in a way that won't break customers of the API.

In any case, I'll go ahead and close this. Please continue to track updates in the other GitHub issue.

**Closed by debora-ito** 2021-07-23 01:29 UTC
Labels: bug, needs-triage
