### ISSUE TITLE
S3 Request signature mismatch for keys containing '+' sign for any XxxObjectRequest operation

### ISSUE THREAD

**Issue by twr** [aws/aws-sdk-java-v2#3474] opened 2022-10-10 11:34 UTC
### Describe the bug

Any XxxObjectRequest (HeadObjectRequest, PutObjectRequest, etc.) operation targeted at specific key containing `+` sign, e.g. `a+b.txt` results in error 'The request signature we calculated does not match the signature you provided. Check your key and signing method.'

This happens using latest sdk v2 library for S3 (and some other older versions tried).

```
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3</artifactId>
    <version>2.17.286</version>
</dependency>
```

### Expected Behavior

No error. Operations succeed as it is for any other keys that do not contain '+' sign.

### Current Behavior

such code:
```
HeadObjectRequest request = HeadObjectRequest.builder()
        .bucket(bucketName)
        .key("a+b.txt")
        .build();

HeadObjectResponse response = s3Client.headObject(request);
```
 
results in:

software.amazon.awssdk.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: S3, Status Code: 403, Request ID: H2E7JCK8TP75G2XA, Extended Request ID: uGN8mJ9U/2/Nn6nyI73MZPA4vpkvo3N2hFr7sG4EkyBDmUNHyMSoWqSXwbNs2F2CfURP994vK8z207G21cBd5Q==)

### Reproduction Steps

```
HeadObjectRequest request = HeadObjectRequest.builder()
        .bucket(bucketName)
        .key("a+b.txt")
        .build();

HeadObjectResponse response = s3Client.headObject(request);
```

### AWS Java SDK version used

2.17.286

### JDK version used

11.0.13

### Operating System and version

macOS 12.6 (21G115)

**Comment by yasminetalby** [comment] 2022-10-10 22:50
Hello @twr ,

I was not able to reproduce the behavior described.
I have attempted both HeadObjectRequest and PutObjectRequest with the key `a+b.txt`" using was Java SDK v2.17.286 following the repro case sample and both completed successfully.
Could you please provide the[ verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) associated with the behavior?

Best,

Yasmine

**Comment by twr** [comment] 2022-10-11 09:42
Hello @yasminetalby, apologies for all the hassle but it seems it is this issue https://github.com/aws/aws-sdk-java/issues/1919
I was testing from within a bigger project that had explicitly set org.apache.httpcomponents:httpclient version to 4.5.7.
My bad, should have tested that in isolation.
This can be closed now.

**Comment by yasminetalby** [comment] 2022-10-11 16:25
Hello @twr, 
No problem at all! Thank you very much for reaching out and for updating this case. 
I will close this issue.
Best,
Yasmine

**Closed by yasminetalby** 2022-10-11 16:25 UTC
Labels: bug
