### ISSUE TITLE
Jars on Maven are compiled with Java SDK 8. What about Java 11?

### ISSUE THREAD

**Issue by zoraida** [aws/aws-sdk-java-v2#1183] opened 2019-04-02 13:49 UTC
Is there any plan to upload to Maven Repository the jars of software.amazon.awssdk artifacts compiled with Java SDK 11?

I am using the s3 artifact and since I compile my project with Java SDK 11, I am getting this exception:

```
java.lang.IncompatibleClassChangeError: Method software.amazon.awssdk.services.s3.S3Client.builder()Lsoftware/amazon/awssdk/services/s3/S3ClientBuilder; must be InterfaceMethodref constant
```
Thanks.

**Comment by brharrington** [comment] 2019-04-02 14:09
That is most likely a problem in the bytecode generated for your app that calls the static method on the interface. JDK 9+ are more strict with some of the validations that are performed. For example, older versions of Groovy are known to have problems: https://github.com/gradle/gradle/issues/721.

At least for my use-cases AWS SDK v2 works fine so far when I'm using JDK11.

**Comment by zoewangg** [comment] 2019-04-03 16:18
Hi @zoraida, are you able to use SDK from Maven repository directly? We don't currently have plans to upload the jars with Java 11. Marking this as a feature request.

Meanwhile, I'd recommend building from the source if using jar is a requirement. See https://github.com/aws/aws-sdk-java-v2#building-from-source

**Comment by zoraida** [comment] 2019-04-23 16:28
> That is most likely a problem in the bytecode generated for your app that calls the static method on the interface. JDK 9+ are more strict with some of the validations that are performed. For example, older versions of Groovy are known to have problems: [gradle/gradle#721](https://github.com/gradle/gradle/issues/721).
> 
> At least for my use-cases AWS SDK v2 works fine so far when I'm using JDK11.

Hi @brharrington, how are you using the sdk? clients must be created by using the static method `builder`. Are you using v2?

https://docs.aws.amazon.com/sdk-for-java/v2/migration-guide/aws-sdk-java-mg.pdf

**Comment by brharrington** [comment] 2019-04-23 20:34
Yes I'm using v2 and I'm not doing anything special. Here is a minimal example [aws2-jdk11](https://github.com/brharrington/aws2-jdk11) and [Travis build](https://travis-ci.org/brharrington/aws2-jdk11/builds/523663495) showing it works fine on openjdk11. There is no issue calling the static builder method from Java using jdk11. 

The problem you are hitting is most likely because of how you are generating the bytecode. Since I'm not familiar with your app I'm not sure what specifically would be the culprit. Can you provide a minimal standalone example that reproduces the failure?

**Comment by zoraida** [comment] 2019-05-02 12:22
Yep! @brharrington  thanks for your response. Our problem was the scala compiler that we currently use. It does not support Java 11 entirely and upgrading to a higher scala compiler is something we cannot afford. 

The primary motivation for using Java 11 was for an easier JVM memory configuration on k8s. Fortunately, a new image was recently build for this propose, thus we finally opted for using it: 

https://blog.softwaremill.com/docker-support-in-new-java-8-finally-fd595df0ca54

Best.

**Comment by brharrington** [comment] 2019-05-02 13:57
FWIW, it works fine for us on jdk11 with scala-2.11.12 and scala-2.12.8.

**Comment by millems** [comment] 2019-07-08 21:47
Closing, as this seems to have been resolved.

**Closed** 2019-07-08 21:47 UTC
Labels: feature-request
