### ISSUE TITLE
Need to upgrade to HttpClient 5.4

### ISSUE THREAD

**Issue by nitulkukadia** [aws/aws-sdk-java-v2#5672] opened 2024-10-21 06:42 UTC
### Describe the bug

Still latest SDK 2.28.26 version software.amazon.awssdk:bom is using , old version of HttpClient 4.x.

Please upgrade to latest version, this is impacting the projects which are using latest HttpClient 5.x.

Used by: software.amazon.awssdk : apache-client : 2.28.26

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

software.amazon.awssdk : apache-client : 2.28.26 be using latest version of HttpClient.

### Current Behavior

software.amazon.awssdk : apache-client : 2.28.26 is using HttpClient 4.x

### Reproduction Steps

Check the dependency tree of software.amazon.awssdk : apache-client : 2.28.26

### Possible Solution

software.amazon.awssdk : apache-client : 2.28.26 be using latest version of HttpClient.

### Additional Information/Context

Keeping an up to date versions of dependency is needed from maintenance and security perspective.

### AWS Java SDK version used

2.0

### JDK version used

java version "17.0.9" 2023-10-17 LTS Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201) Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)

### Operating System and version

macOS Sonoma 14.6.1

**Comment by debora-ito** [comment] 2024-10-21 16:42
Duplicate of https://github.com/aws/aws-sdk-java-v2/issues/2831. Please track the progress and discussion in that link.

**Closed by debora-ito** 2024-10-21 16:42 UTC
Labels: bug, needs-triage
