### ISSUE TITLE
Kinesis ApproximateArrivalTimestamp is not parsed correctly in cbor unmarshaller

### ISSUE THREAD

**Issue by ffriedrich** [aws/aws-sdk-java-v2#184] opened 2017-09-27 07:32 UTC
When I call ```get-records``` via aws cli I get timestamps with a decimal point like this:
            ```"ApproximateArrivalTimestamp":  1506440188.749, ```

This is equivalent to  "09/26/2017 @ 3:36pm (UTC)".

When you use the cbor format, the sdk parses this as "03/11/49707 @ 7:59am (UTC)" which is obviously wrong.

(see /core-2.0.0-preview-4-sources.jar!/software/amazon/awssdk/runtime/transform/SimpleTypeCborUnmarshallers.java:221)

The json unmarshalling works fine, so a workaround is to disable cbor:
``` System.setProperty("aws.cborEnabled", "false");```

**Comment by ffriedrich** [comment] 2017-09-27 07:37
The bug seems to be in ```software.amazon.awssdk.util.DateUtils#parseServiceSpecificInstant```.
Here the date string is scaled by 10^3 to get milli precision, but the string already has milli precision. If you omit the scaling, you get the correct result.

**Comment by millems** [comment] 2017-09-27 18:59
Double checking to make sure this isn't also an issue with v1...

**Comment by millems** [comment] 2017-09-27 19:46
Cool, just in V2. Looking to see what the cause is...

**Comment by millems** [comment] 2017-09-27 20:38
It looks like the CBOR representation lacks the decimal point. In V1 we parse it as a long, but ended up changing it in V2 for some reason. It's a quick fix thanks to your detailed bug report!

**Comment by millems** [comment] 2017-09-27 21:43
The fix for this issue should go out with preview-5. Thanks again for your detailed report!

**Closed** 2017-09-27 21:42 UTC
Labels: Investigating
