### ISSUE TITLE
DynamoDbEnhancedClient: Support for polymorphic types

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#1917] opened 2020-06-22 21:40 UTC
From https://github.com/aws/aws-sdk-java-v2/issues/35:

https://github.com/aws/aws-sdk-java/issues/832

**Comment by debora-ito** [comment] 2020-06-24 19:00
Duplicate of https://github.com/aws/aws-sdk-java-v2/issues/1870.

**Closed by debora-ito** 2020-06-24 19:00 UTC
Labels: dynamodb-enhanced, feature-request
