### ISSUE TITLE
OOM when get a range of large object

### ISSUE THREAD

**Issue by zymap** [aws/aws-sdk-java-v2#2617] opened 2021-07-22 14:25 UTC
## Describe the bug
I am using the sdk to download an object with range, but the program will happen OOM in my application. I test it on local to download the object with a given range, the heap memory will increase continually and the get response is stuck. I am not sure I was using the API correctly.

Here is my download code:

```
        String bucket = "yong-dev-backuprestore";
        StaticCredentialsProvider provider = StaticCredentialsProvider.create(AwsBasicCredentials.create("id", "secret"));
        S3Client s3Client = S3Client.builder()
            .credentialsProvider(provider)
            .region(Region.AP_SOUTHEAST_1)
            .build();
        String key = "e7470efd-654a-4d1d-a38b-7d2c6c96b86c-ledger-1";
        GetObjectRequest request = GetObjectRequest.builder()
            .bucket(bucket)
            .key(key)
            .range("byte=0-9")
            .build();
        ResponseBytes<GetObjectResponse> responseBytes = s3Client.getObjectAsBytes(request); // the program will stuck at here and the memory will increase
        try (InputStream inputStream = responseBytes.asInputStream()) {
            int read;
            while ((read = inputStream.read()) > 0) {
                System.out.println(read);
            }
        }
        s3Client.close();
```

The error stack is:

```
java.lang.OutOfMemoryError.<init>() OutOfMemoryError.java
java.util.Arrays.copyOf(byte[], int) Arrays.java:3745
java.io.ByteArrayOutputStream.grow(int) ByteArrayOutputStream.java:120
java.io.ByteArrayOutputStream.ensureCapacity(int) ByteArrayOutputStream.java:95
java.io.ByteArrayOutputStream.write(byte[], int, int) ByteArrayOutputStream.java:156
software.amazon.awssdk.utils.IoUtils.toByteArray(InputStream) IoUtils.java:48
software.amazon.awssdk.core.sync.ResponseTransformer.lambda$toBytes$3(Object, AbortableInputStream) ResponseTransformer.java:175
software.amazon.awssdk.core.sync.ResponseTransformer$$Lambda$932.transform(Object, AbortableInputStream)
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler$HttpResponseHandlerAdapter.transformResponse(SdkResponse, AbortableInputStream) BaseSyncClientHandler.java:212
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler$HttpResponseHandlerAdapter.handle(SdkHttpFullResponse, ExecutionAttributes) BaseSyncClientHandler.java:200
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(SdkHttpFullResponse, ExecutionAttributes) CombinedResponseHandler.java:97
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(SdkHttpFullResponse, ExecutionAttributes) CombinedResponseHandler.java:72
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(SdkHttpFullResponse, ExecutionAttributes) CombinedResponseHandler.java:59
software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(SdkHttpFullResponse, ExecutionAttributes) CombinedResponseHandler.java:40
software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(SdkHttpFullResponse, RequestExecutionContext) HandleResponseStage.java:40
software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(Object, RequestExecutionContext) HandleResponseStage.java:30
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(Object, RequestExecutionContext) RequestPipelineBuilder.java:206
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(SdkHttpFullRequest, RequestExecutionContext) ApiCallAttemptTimeoutTrackingStage.java:73
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(Object, RequestExecutionContext) ApiCallAttemptTimeoutTrackingStage.java:42
software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(SdkHttpFullRequest, RequestExecutionContext) TimeoutExceptionHandlingStage.java:78
software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(Object, RequestExecutionContext) TimeoutExceptionHandlingStage.java:40
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(SdkHttpFullRequest, RequestExecutionContext) ApiCallAttemptMetricCollectionStage.java:50
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(Object, RequestExecutionContext) ApiCallAttemptMetricCollectionStage.java:36
software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(SdkHttpFullRequest, RequestExecutionContext) RetryableStage.java:64
software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(Object, RequestExecutionContext) RetryableStage.java:34
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(Object, RequestExecutionContext) RequestPipelineBuilder.java:206
software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(SdkHttpFullRequest, RequestExecutionContext) StreamManagingStage.java:56
software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(Object, RequestExecutionContext) StreamManagingStage.java:36
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(SdkHttpFullRequest, RequestExecutionContext) ApiCallTimeoutTrackingStage.java:80
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(SdkHttpFullRequest, RequestExecutionContext) ApiCallTimeoutTrackingStage.java:60
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(Object, RequestExecutionContext) ApiCallTimeoutTrackingStage.java:42
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(SdkHttpFullRequest, RequestExecutionContext) ApiCallMetricCollectionStage.java:48
software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(Object, RequestExecutionContext) ApiCallMetricCollectionStage.java:31
software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(Object, RequestExecutionContext) RequestPipelineBuilder.java:206  <2 recursive calls>
software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(SdkHttpFullRequest, RequestExecutionContext) ExecutionFailureExceptionReportingStage.java:37
software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(Object, RequestExecutionContext) ExecutionFailureExceptionReportingStage.java:26
software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(HttpResponseHandler) AmazonSyncHttpClient.java:193
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(SdkHttpFullRequest, SdkRequest, ExecutionContext, HttpResponseHandler) BaseSyncClientHandler.java:135
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(ClientExecutionParams, ExecutionContext, HttpResponseHandler) BaseSyncClientHandler.java:161
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$0(ClientExecutionParams, ResponseTransformer) BaseSyncClientHandler.java:84
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler$$Lambda$935.get()
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(ClientExecutionParams, Supplier) BaseSyncClientHandler.java:169
software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(ClientExecutionParams, ResponseTransformer) BaseSyncClientHandler.java:62
software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(ClientExecutionParams, ResponseTransformer) SdkSyncClientHandler.java:52
software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(ClientExecutionParams, ResponseTransformer) AwsSyncClientHandler.java:62
software.amazon.awssdk.services.s3.DefaultS3Client.getObject(GetObjectRequest, ResponseTransformer) DefaultS3Client.java:4370
software.amazon.awssdk.services.s3.S3Client.getObjectAsBytes(GetObjectRequest) S3Client.java:8121
io.streamnative.aws.offloader.format.BlobStoreBackedInputStreamImpl.refillBufferIfNeeded() BlobStoreBackedInputStreamImpl.java:83
io.streamnative.aws.offloader.format.BlobStoreBackedInputStreamImpl.read() BlobStoreBackedInputStreamImpl.java:107
java.io.DataInputStream.readInt() DataInputStream.java:392
io.streamnative.aws.offloader.format.BlobStoreBackedReadHandleImpl.lambda$readAsync$1(long, long, CompletableFuture) BlobStoreBackedReadHandleImpl.java:108
io.streamnative.aws.offloader.format.BlobStoreBackedReadHandleImpl$$Lambda$1165.run()
java.util.concurrent.Executors$RunnableAdapter.call() Executors.java:515
com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly() TrustedListenableFutureTask.java:125
com.google.common.util.concurrent.InterruptibleTask.run() InterruptibleTask.java:69
com.google.common.util.concurrent.TrustedListenableFutureTask.run() TrustedListenableFutureTask.java:78
java.util.concurrent.Executors$RunnableAdapter.call() Executors.java:515
java.util.concurrent.FutureTask.run() FutureTask.java:264
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() ScheduledThreadPoolExecutor.java:304
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1128
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:628
io.netty.util.concurrent.FastThreadLocalRunnable.run() FastThreadLocalRunnable.java:30
java.lang.Thread.run() Thread.java:829

```

## Your Environment

* AWS Java SDK version used: 2.16.60
* JDK version used: 1.8
* Operating System and version: macOS 11.4

**Comment by zymap** [comment] 2021-07-23 09:40
I found the reason which is because the range is `byte` not the `bytes`. But I think it's weird that the program will OOM caused by the wrong range value.

**Comment by debora-ito** [comment] 2021-07-29 18:51
Hi @zymap you're seeing out of memory errors because the code is reading the whole inputstream and holding it in memory. A simple improvement would be to use a buffer array to read the inputstream and write that buffer into a outputstream iteratively. Something like:

```java
byte[] buffer = new byte[1024];

try (FileOutputStream outputStream = new FileOutputStream(PATH)) {
    while ((inputStream.read(buffer)) != -1) {
        outputStream.write(buffer);
    }
}
```

There's also other options like using BufferedInputStream, you can look for tutorials on the internet on how to manage large files in Java.

Closing this, as the issue is not related to the Java SDK itself. Feel free to reach out if you have other questions.

**Closed by debora-ito** 2021-07-29 18:51 UTC
Labels: guidance
