### ISSUE TITLE
Add endpointOverride option to TransferManager S3ClientConfiguration

### ISSUE THREAD

**Issue by saso5** [aws/aws-sdk-java-v2#3102] opened 2022-03-16 12:12 UTC
### Describe the feature

Add `endpointOverride` option to TransferManager `S3ClientConfiguration` as in `S3ClientBuilder`
https://github.com/aws/aws-sdk-java-v2/blob/4bf4d3a54b1ae98fd45a73e140b180c57b6a11d3/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkClientBuilder.java

### Is your Feature Request related to a problem?

I can't run end2end tests with localstack.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

s3-transfer-manager:2.17.146-PREVIEW

### JDK version used

Java 11

### Operating System and version

Windows 10

**Comment by debora-ito** [comment] 2022-03-16 17:12
Duplicate of https://github.com/aws/aws-sdk-java-v2/issues/2740.
There's a PR in the works already, please use the issue above to track progress.

**Closed by debora-ito** 2022-03-16 17:12 UTC
Labels: feature-request, duplicate
