### ISSUE TITLE
java.lang.NoClassDefFoundError: software/amazon/awssdk/http/async/AbortableRunnable

### ISSUE THREAD

**Issue by soaked-towel** [aws/aws-sdk-java-v2#1382] opened 2019-08-13 14:51 UTC
## Current Behavior
Getting an exception when using awssdk:s3

I get this exception when i use awssdk:s3 >= 2.6.5
```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NullPointerException
```

But if i add software.amazon.awssdk:netty-nio-client:2.0.0 to gradle i get this exception.

`java.lang.NoClassDefFoundError: software/amazon/awssdk/http/async/AbortableRunnable`

## Stacktrace

AWSSDK:S3 >= 2.6.5
```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NullPointerException
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:136)
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:104)
	at ch.qos.logback.core.joran.spi.ConfigurationWatchList.convertToFile(ConfigurationWatchList.java:95)
	at ch.qos.logback.core.joran.spi.ConfigurationWatchList.addAsFileToWatch(ConfigurationWatchList.java:59)
	at ch.qos.logback.core.joran.spi.ConfigurationWatchList.setMainURL(ConfigurationWatchList.java:55)
	at ch.qos.logback.core.joran.util.ConfigurationWatchListUtil.setMainWatchURL(ConfigurationWatchListUtil.java:50)
	at ch.qos.logback.core.joran.GenericConfigurator.informContextOfURLUsedForConfiguration(GenericConfigurator.java:100)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:46)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient.<clinit>(NettyNioAsyncHttpClient.java:75)
	at com.alexander_co.aws.AWSTest.getS3Object(AWSTest.kt:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/C:/Users/asljb/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.36.Final/f6f38fde652a70ea579897edc80e52353e487ae6/netty-common-4.1.36.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Added software.amazon.awssdk:netty-nio-client:2.0.0 to gradle

```
java.lang.NoClassDefFoundError: software/amazon/awssdk/http/async/AbortableRunnable
	at com.alexander_co.aws.AWSTest.getS3Object(AWSTest.kt:22)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.http.async.AbortableRunnable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

## Gradle

```
dependencies {
    compile "ch.qos.logback:logback-classic:$logback_version"
    compile "com.github.jasync-sql:jasync-mysql:1.0.5"
    compile "io.ktor:ktor-server-netty:$ktor_version"
    compile "io.ktor:ktor-server-core:$ktor_version"
    compile "io.ktor:ktor-server-sessions:$ktor_version"
    compile "io.ktor:ktor-client-core:$ktor_version"
    compile "io.ktor:ktor-client-core-jvm:$ktor_version"
    implementation "io.ktor:ktor-network-tls:$ktor_version"
    compile "com.google.guava:guava:28.0-jre"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.1"
    implementation "com.google.code.gson:gson:2.8.5"
    testCompile "io.ktor:ktor-server-tests:$ktor_version"
    compile "software.amazon.awssdk:s3:2.7.22"
    compile "software.amazon.awssdk:netty-nio-client:2.0.0"
}
```

## Steps to Reproduce (for bugs)
This is the only code i try to run when i get this error.
```
import kotlinx.coroutines.runBlocking
import software.amazon.awssdk.http.nio.netty.NettyNioAsyncHttpClient
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.s3.S3AsyncClient
import java.util.*
import kotlin.test.Test

class AWSTest {

    @Test
    fun getS3Object() {
        val prop = Properties()
        prop.setProperty("aws.accessKeyId", "************")
        prop.setProperty("aws.secretAccessKey", "*****************************")
        System.setProperties(prop)

        // NullPointerException
        //val s3 = S3AsyncClient.create()
        
        // NullPointerException
        val s3 = S3AsyncClient.builder()
            .httpClientBuilder(
                NettyNioAsyncHttpClient.builder()
                    .maxConcurrency(50)
                    .maxPendingConnectionAcquires(1000))
            .build()

        runBlocking {
            //s3.getObject("dzr_194093615;263;2018_02_05_10_41_43;1.jpg")
        }
    }
}
```

## Context
Trying to upload and download files from my s3 buckets.

## Your Environment
* AWS Java SDK version used: 2.6.5, 2.7.17 & 2.7.22
* JDK version used: OpenJDK 12.0.1 (2019-04-16)
* Operating System and version: Windows 10 64-bit (Version 1809 Build 17763.615)

**Comment by debora-ito** [comment] 2019-08-13 18:35
@soaked-towel The `NoClassDefFoundError` exception is probably caused by using different versions of s3 and netty-nio-client. Can you upgrade the netty-nio-client to the same version of s3,  `2.7.22` in this case?

**Comment by soaked-towel** [comment] 2019-08-13 18:37
In my post i put the stacktrace when both are the same version I get a NullPointerException but nothing tells me what is null. All my variables are not null.

**Comment by debora-ito** [comment] 2019-08-13 18:51
They are not in the same version, according to your gradle file:

```
    compile "software.amazon.awssdk:s3:2.7.22"
    compile "software.amazon.awssdk:netty-nio-client:2.0.0"
```

Not sure what's the cause of `NullPointerException`, it's being thrown by `ch.qos.logback` which is not an SDK dependency.

**Comment by soaked-towel** [comment] 2019-08-15 12:42
Hey debora-ito. Yes it shows up in the gradle file I pasted but I already tried removing it and made both the same version and that when i get the NullPointerReference rather than the ClassNotFound.

You are right though it does seem to be ch.qos.logback which is a dependency of ktor but ktor runs and uses logback just fine so I'm still at a lost here.

**Comment by debora-ito** [comment] 2019-08-15 21:44
So in this case I would look for the logback team support, it looks like their project is on Github: https://github.com/qos-ch/logback

I'll go ahead and close this since the issue with the SDK has been resolved. Feel free to reopen if you have further questions.

**Closed by debora-ito** 2019-08-15 21:44 UTC
Labels: guidance
