### ISSUE TITLE
SQSAsyncClient generates TimeoutException: Acquire operation took longer then configured

### ISSUE THREAD

**Issue by nakolkin** [aws/aws-sdk-java-v2#290] opened 2017-11-17 11:29 UTC
## Current Behavior

I’m trying to receive messages by using SQSAsyncClient in the endless loop and getting: 
`java.util.concurrent.TimeoutException: Acquire operation took longer then configured maximum time`
Not sure if this is expected behavior? 

Full stack trace: [stacktrace.log](https://github.com/aws/aws-sdk-java-v2/files/1482081/stacktrace.log)

## Steps to Reproduce (for bugs)
```java
    public static void main(String[] args) {

        AwsCredentials creds = new AwsCredentials(ACCESS_KEY_ID, SECRET_ACCESS_KEY);

        SQSAsyncClient sqsAsyncClient = SQSAsyncClient.builder()
            .credentialsProvider(new StaticCredentialsProvider(creds))
            .build();

        GetQueueUrlRequest urlRequest = GetQueueUrlRequest.builder()
            .queueName(QUEUE_NAME)
            .build();

        String queueUrl = sqsAsyncClient.getQueueUrl(urlRequest).join().queueUrl();

        logger.debug("Receive messages");
        ReceiveMessageRequest receiveMessageRequest = ReceiveMessageRequest.builder()
            .queueUrl(queueUrl)
            .build();

        while (true) {
            sqsAsyncClient.receiveMessage(receiveMessageRequest)
                .whenCompleteAsync((resp, err) -> {
                    if (resp != null) {
                        resp.messages()
                            .forEach(message -> {
                                logger.debug(message.messageId());
                            });
                    } else {
                        err.printStackTrace();
                    }
                });
        }
    }
```
## Your Environment

* AWS Java SDK version used: preview-5
* JDK version used: jdk1.8.0_144
* Operating System and version: macOS High Sierra 10.13.1

**Comment by zeldigas** [comment] 2017-11-20 19:08
Not sure if relates to root cause, but strange that you are not waiting call to complete before sending next request. As async client does not block I'll not surprise if sample code does thousands of requests in this while true loop.

Have you tried introducing a barrier that's released in callback?

**Comment by nakolkin** [comment] 2017-11-23 10:53
Hey @zeldigas, my wrong expectation was that at some point the next request will be blocked until a resource is available again. And it doesn't work this way with non-blocking API. So I fixed my issue with the `Semaphore` which limits open calls in-flight .

**Comment by millems** [comment] 2018-01-30 23:25
Please let us know if you have any more questions!

**Closed by millems** 2018-01-30 23:25 UTC

**Comment by btkotte** [comment] 2020-08-03 15:03
@nakolkin Can you share the code snippet of how you fixed this. Thanks
